import Link from "next/link";
import { redirect } from "next/navigation";
import { Alert } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { PageContainer, PageHeader } from "@/components/ui/page-layout";
import { getAccessContext } from "@/lib/access/context";
import { getRecentShiftHistory, getShiftReconciliation } from "@/lib/d1/closing";
import { getD1SchemaStatus } from "@/lib/d1/context";
import { getOpenShift } from "@/lib/d1/teller";
import { closeShiftAction } from "@/app/teller/actions";
import styles from "./closing.module.css";

export const dynamic="force-dynamic";
type PageProps={searchParams:Promise<{status?:string;error?:string;variance?:string}>};
function rupiah(value:number){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(value);}
function timestamp(value:string|null){if(!value)return"—";return new Date(value).toLocaleString("id-ID",{timeZone:"Asia/Jakarta",dateStyle:"medium",timeStyle:"short"});}

export default async function ClosingPage({searchParams}:PageProps){
 const access=await getAccessContext();if(!access)redirect("/login");if(!access.permissions.includes("POS_ACCESS")&&!access.permissions.includes("REPORT_VIEW"))redirect("/dashboard");const d1=await getD1SchemaStatus();if(!d1.initialized)redirect("/setup/database");
 const params=await searchParams;const variance=Number(params.variance??"0");const [openShift,history]=await Promise.all([getOpenShift(access.organization.id,access.user.id),getRecentShiftHistory(access.organization.id,12)]);const reconciliation=openShift?await getShiftReconciliation(access.organization.id,openShift.id):null;
 return <PageContainer size="full">
  <PageHeader eyebrow="Kontrol Kas · Rekonsiliasi" title="Penutupan & Rekonsiliasi Kasir" description="Shift hanya boleh ditutup ketika penjualan, pembayaran, stok, jurnal, dan transaksi Simpanan konsisten. Selisih kas tetap dicatat di audit trail." actions={<div className={styles.actions}><Link href="/teller">Kasir / Shift</Link><Link href="/reports/daily-sales">Laporan Harian</Link></div>}/>
  {params.status==="shift-closed"?<Alert tone={variance===0?"success":"warning"}>Shift berhasil ditutup. Selisih kas tercatat {rupiah(variance)}.</Alert>:null}{params.error?<Alert tone="danger">{params.error}</Alert>:null}
  {openShift&&reconciliation?<>
   <section className={styles.metrics}><Card density="compact"><span>Kas awal</span><strong>{rupiah(reconciliation.shift.opening_cash_amount)}</strong><small>{timestamp(reconciliation.shift.opened_at)}</small></Card><Card density="compact"><span>Transaksi penjualan</span><strong>{reconciliation.metrics.committedTransactions}</strong><small>{reconciliation.metrics.voidedTransactions} void</small></Card><Card density="compact"><span>Omzet committed</span><strong>{rupiah(reconciliation.metrics.committedSalesAmount)}</strong><small>semua metode</small></Card><Card density="compact"><span>Penjualan tunai</span><strong>{rupiah(reconciliation.metrics.cashConfirmedAmount)}</strong><small>masuk cash drawer</small></Card><Card density="compact"><span>Arus kas Simpanan</span><strong>{rupiah(reconciliation.metrics.savingsCashDeltaAmount)}</strong><small>{reconciliation.metrics.savingsTransactionCount} transaksi</small></Card><Card density="compact"><span>Kas seharusnya</span><strong>{rupiah(reconciliation.metrics.expectedCashAmount)}</strong><small>kas awal + penjualan + simpanan</small></Card><Card density="compact" className={reconciliation.passed?styles.passMetric:styles.failMetric}><span>Integritas</span><strong>{reconciliation.passed?"PASS":"CHECK"}</strong><small>{reconciliation.metrics.issueCount} exception</small></Card></section>
   <section className={styles.reconGrid}><Card className={styles.panel}><div className={styles.panelHeader}><div><span className={styles.kicker}>PEMERIKSAAN TRANSAKSI</span><h2>{reconciliation.passed?"Semua transaksi konsisten":"Exception harus diperiksa"}</h2></div><Badge tone={reconciliation.passed?"success":"warning"}>{reconciliation.passed?"PASS":`${reconciliation.metrics.issueCount} CHECK`}</Badge></div>{reconciliation.issues.length?<div className={styles.issueList}>{reconciliation.issues.map((issue,index)=><article className={styles.issue} key={`${issue.saleId}-${issue.code}-${index}`}><div><Badge tone="warning">{issue.code}</Badge><strong>{issue.receiptNumber}</strong><p>{issue.message}</p></div><Link href={issue.code==="SAVINGS_JOURNAL"?"/savings/accounts":`/sales/${issue.saleId}`}>{issue.code==="SAVINGS_JOURNAL"?"Periksa rekening":"Periksa struk"}</Link></article>)}</div>:<Alert tone="success">Penjualan, pembayaran, stok, jurnal, dan transaksi Simpanan pada shift ini sudah cocok.</Alert>}</Card>
    <Card className={styles.panel}><span className={styles.kicker}>HITUNG KAS</span><h2>Tutup cash drawer</h2><p className={styles.copy}>Hitung uang fisik terlebih dahulu. Kas seharusnya tidak boleh diubah agar selisih dapat dilacak.</p><div className={styles.expected}><span>Kas seharusnya</span><strong>{rupiah(reconciliation.metrics.expectedCashAmount)}</strong></div><form action={closeShiftAction} className={styles.closeForm}><label>Kas fisik yang dihitung<input name="countedCashAmount" inputMode="numeric" defaultValue={reconciliation.metrics.expectedCashAmount} required/></label><button type="submit" disabled={!reconciliation.passed}>{reconciliation.passed?"Tutup Shift & Catat Rekonsiliasi":"Perbaiki exception terlebih dahulu"}</button></form><small className={styles.note}>Penutupan menyimpan kas seharusnya, kas fisik, selisih, jumlah transaksi, dan status rekonsiliasi ke jejak audit.</small></Card></section>
  </>:<Card className={styles.noShift}><Badge tone="neutral">TIDAK ADA SHIFT AKTIF</Badge><h2>Tidak ada shift aktif untuk akun ini.</h2><p>Buka shift dari Workspace Kasir jika ingin memulai transaksi tunai baru.</p><Link href="/teller">Kembali ke Kasir / Shift</Link></Card>}
  <Card className={styles.historyPanel}><div className={styles.panelHeader}><div><span className={styles.kicker}>RIWAYAT SHIFT</span><h2>12 shift terakhir organisasi</h2></div><Link href="/reports/daily-sales">Lihat laporan penjualan</Link></div>{history.length?<div className={styles.tableWrap}><table><thead><tr><th>Dibuka</th><th>Status</th><th>Transaksi</th><th>Omzet</th><th>Kas seharusnya</th><th>Kas fisik</th><th>Selisih</th></tr></thead><tbody>{history.map(shift=><tr key={shift.id}><td>{timestamp(shift.opened_at)}</td><td><Badge tone={shift.status==="OPEN"?"warning":"success"}>{shift.status}</Badge></td><td>{shift.transaction_count}</td><td>{rupiah(shift.committed_sales_amount)}</td><td>{shift.expected_cash_amount==null?"—":rupiah(shift.expected_cash_amount)}</td><td>{shift.counted_cash_amount==null?"—":rupiah(shift.counted_cash_amount)}</td><td className={Number(shift.variance_amount??0)===0?styles.zeroVariance:styles.hasVariance}>{shift.variance_amount==null?"—":rupiah(shift.variance_amount)}</td></tr>)}</tbody></table></div>:<div className={styles.empty}>Belum ada riwayat shift.</div>}</Card>
 </PageContainer>;
}
