import Link from "next/link";
import { redirect } from "next/navigation";
import { getAccessContext } from "@/lib/access/context";
import { getD1SchemaStatus } from "@/lib/d1/context";
import { listProductsWithStock } from "@/lib/d1/inventory";
import { listPurchaseOrders,listPurchaseRequests,listSuppliers } from "@/lib/d1/procurement";
import { PageContainer,PageHeader } from "@/components/ui/page-layout";
import { Card } from "@/components/ui/card";
import { Alert } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { approvePurchaseRequestAction,createPurchaseOrderAction,createSupplierAction,rejectPurchaseRequestAction } from "./actions";
import PrComposer from "./pr-composer";
import styles from "./procurement.module.css";

export const dynamic="force-dynamic";
type PageProps={searchParams:Promise<{status?:string;error?:string}>};
function rupiah(value:number){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(value)}
function dateTime(value:string|null){if(!value)return"—";return new Date(value).toLocaleString("id-ID",{timeZone:"Asia/Jakarta",dateStyle:"short",timeStyle:"short"})}
function statusText(status:string){const map:Record<string,string>={SUBMITTED:"Menunggu persetujuan",APPROVED:"Disetujui",REJECTED:"Ditolak",PO_CREATED:"PO dibuat",DRAFT:"Draft",ISSUED:"Diterbitkan",PARTIALLY_RECEIVED:"Diterima sebagian",RECEIVED:"Diterima penuh",CLOSED:"Selesai"};return map[status]||status}
function statusTone(status:string):"success"|"warning"|"danger"|"info"|"neutral"{if(["APPROVED","RECEIVED","CLOSED"].includes(status))return"success";if(status==="REJECTED")return"danger";if(["SUBMITTED","PARTIALLY_RECEIVED"].includes(status))return"warning";if(["DRAFT","ISSUED","PO_CREATED"].includes(status))return"info";return"neutral"}

export default async function ProcurementPage({searchParams}:PageProps){
 const access=await getAccessContext();if(!access)redirect("/login");const canViewPurchase=access.permissions.includes("PURCHASE_VIEW");const canViewSupplier=access.permissions.includes("SUPPLIER_VIEW");if(!canViewPurchase&&!canViewSupplier)redirect("/dashboard");
 const schema=await getD1SchemaStatus();if(!schema.current)redirect("/setup/database");const params=await searchParams;
 const [suppliers,purchaseRequests,purchaseOrders,products]=await Promise.all([listSuppliers(access.organization.id),canViewPurchase?listPurchaseRequests(access.organization.id,100):Promise.resolve([]),canViewPurchase?listPurchaseOrders(access.organization.id,100):Promise.resolve([]),canViewPurchase?listProductsWithStock(access.organization.id):Promise.resolve([])]);
 const activeSuppliers=suppliers.filter((supplier)=>supplier.status==="ACTIVE");const activeProducts=products.filter((product)=>product.status==="ACTIVE");const pending=purchaseRequests.filter((pr)=>pr.status==="SUBMITTED");const approvedWithoutPo=purchaseRequests.filter((pr)=>pr.status==="APPROVED");const openPos=purchaseOrders.filter((po)=>["DRAFT","ISSUED","PARTIALLY_RECEIVED"].includes(po.status));
 const canManageSupplier=access.permissions.includes("SUPPLIER_MANAGE");const canCreate=access.permissions.includes("PURCHASE_CREATE");const canApprove=access.permissions.includes("PURCHASE_APPROVE");const canPo=access.permissions.includes("PO_MANAGE");
 return <PageContainer size="full">
  <PageHeader eyebrow="Operasional · Pembelian" title="Supplier & Pembelian" description="Permintaan pembelian, persetujuan, PO, penerimaan barang, dan supplier berada dalam satu jejak transaksi. Pembuat PR tidak dapat menyetujui PR miliknya sendiri." actions={<div className={styles.topActions}><Link className={styles.detailLink} href="/procurement/ap">Hutang Pemasok</Link><Link className={styles.detailLink} href="/inventory">Stok & Gudang</Link></div>}/>
  {params.status?<Alert tone="success" title="Proses berhasil">{params.status.replace(/-/g," ")}.</Alert>:null}
  {params.error?<Alert tone="danger" title="Pembelian belum dapat diproses">{params.error}</Alert>:null}

  <section className={styles.metrics}>
   <Card density="compact"><span>Supplier aktif</span><strong>{activeSuppliers.length}</strong><small>dari {suppliers.length} supplier</small></Card>
   <Card density="compact"><span>PR menunggu</span><strong>{pending.length}</strong><small>perlu keputusan checker</small></Card>
   <Card density="compact"><span>PR siap PO</span><strong>{approvedWithoutPo.length}</strong><small>sudah disetujui</small></Card>
   <Card density="compact"><span>PO terbuka</span><strong>{openPos.length}</strong><small>draft / terbit / sebagian</small></Card>
  </section>

  {canCreate?<Card className={styles.panel}><div className={styles.panelHeader}><div><span className={styles.kicker}>PERMINTAAN PEMBELIAN</span><h3>Buat kebutuhan pembelian</h3></div><Badge tone="info">MAKER</Badge></div>{activeProducts.length?<PrComposer products={activeProducts.map((product)=>({id:product.id,sku:product.sku,name:product.name,unit_name:product.unit_name,cost_amount:product.cost_amount}))} suppliers={activeSuppliers.map((supplier)=>({id:supplier.id,code:supplier.code,name:supplier.name}))}/>:<div className={styles.empty}>Belum ada produk aktif. Buat Master Produk lebih dulu.</div>}</Card>:null}

  <section className={styles.twoPanel}>
   <Card className={styles.panel}><div className={styles.panelHeader}><div><span className={styles.kicker}>MENUNGGU PERSETUJUAN</span><h3>PR yang perlu keputusan</h3></div><Badge tone={pending.length?"warning":"success"}>{pending.length}</Badge></div>{pending.length?<div className={styles.cardList}>{pending.map((pr)=><div className={styles.requestCard} key={pr.id}><div className={styles.requestHead}><div><strong>{pr.pr_number}</strong><span>{dateTime(pr.submitted_at)} · {pr.item_count} item</span></div><b>{rupiah(pr.total_estimated_amount)}</b></div><p>{pr.notes||"Tanpa catatan"}</p><div className={styles.requestMeta}><span>Supplier: {pr.supplier_name||"belum ditentukan"}</span><span>Maker: {pr.requested_by.slice(0,8)}</span></div>{canApprove?<div className={styles.decisionRow}><form action={approvePurchaseRequestAction}><input type="hidden" name="purchaseRequestId" value={pr.id}/><button className={styles.approveButton} type="submit">Setujui</button></form><form action={rejectPurchaseRequestAction} className={styles.rejectForm}><input type="hidden" name="purchaseRequestId" value={pr.id}/><input name="reason" minLength={8} required placeholder="Alasan penolakan"/><button className={styles.rejectButton} type="submit">Tolak</button></form></div>:<span className={styles.muted}>Hanya dapat melihat; tidak memiliki hak persetujuan.</span>}</div>)}</div>:<div className={styles.empty}>Tidak ada PR yang menunggu persetujuan.</div>}</Card>

   <Card className={styles.panel}><div className={styles.panelHeader}><div><span className={styles.kicker}>MASTER SUPPLIER</span><h3>Supplier</h3></div><Badge>{suppliers.length}</Badge></div>{canManageSupplier?<form action={createSupplierAction} className={styles.supplierForm}><div className={styles.formGrid2}><label>Kode<input name="code" required maxLength={30} placeholder="SUP-001"/></label><label>Nama<input name="name" required maxLength={120} placeholder="Nama supplier"/></label><label>Kontak<input name="contactName" placeholder="PIC supplier"/></label><label>Telepon<input name="phone" placeholder="08..."/></label><label>Email<input name="email" type="email" placeholder="Opsional"/></label><label>Termin hari<input name="paymentTermsDays" type="number" min="0" max="365" defaultValue="0"/></label></div><label>NPWP / Tax ID<input name="taxId" placeholder="Opsional"/></label><label>Alamat<textarea name="address" maxLength={300} placeholder="Alamat supplier"/></label><button className={styles.primaryButton} type="submit">Simpan Supplier</button></form>:null}<div className={styles.supplierList}>{suppliers.slice(0,12).map((supplier)=><div key={supplier.id}><strong>{supplier.name}</strong><span>{supplier.code} · {supplier.payment_terms_days} hari · {supplier.status}</span></div>)}{!suppliers.length?<div className={styles.empty}>Belum ada supplier.</div>:null}</div></Card>
  </section>

  {canPo?<Card className={styles.panel}><div className={styles.panelHeader}><div><span className={styles.kicker}>PR DISETUJUI → PO</span><h3>Buat PO dari PR yang disetujui</h3></div><Badge tone="info">{approvedWithoutPo.length}</Badge></div>{approvedWithoutPo.length?<div className={styles.poCreateGrid}>{approvedWithoutPo.map((pr)=><form action={createPurchaseOrderAction} className={styles.poCreateCard} key={pr.id}><input type="hidden" name="purchaseRequestId" value={pr.id}/><div><strong>{pr.pr_number}</strong><span>{pr.item_count} item · {rupiah(pr.total_estimated_amount)}</span></div><label>Supplier<select name="supplierId" defaultValue={pr.preferred_supplier_id||""} required><option value="" disabled>Pilih supplier</option>{activeSuppliers.map((supplier)=><option key={supplier.id} value={supplier.id}>{supplier.code} · {supplier.name}</option>)}</select></label><label>Perkiraan tanggal<input name="expectedDate" type="date"/></label><label>Catatan<input name="notes" maxLength={200} placeholder="Opsional"/></label><button className={styles.primaryButton} type="submit" disabled={!activeSuppliers.length}>Buat Draft PO</button></form>)}</div>:<div className={styles.empty}>Belum ada PR disetujui yang menunggu PO.</div>}</Card>:null}

  <Card className={styles.panel}><div className={styles.panelHeader}><div><span className={styles.kicker}>PURCHASE ORDER</span><h3>PO & status penerimaan</h3></div><Badge>{purchaseOrders.length}</Badge></div>{purchaseOrders.length?<div className={`${styles.tableWrap} ${styles.mobileRegistry}`}><table><thead><tr><th>PO / PR</th><th>Supplier</th><th>Nilai</th><th>Penerimaan</th><th>Status</th><th></th></tr></thead><tbody>{purchaseOrders.map((po)=><tr key={po.id}><td data-label="PO / PR"><strong>{po.po_number}</strong><span>{po.pr_number} · {dateTime(po.created_at)}</span></td><td data-label="Supplier"><strong>{po.supplier_name}</strong><span>{po.supplier_code}</span></td><td data-label="Nilai"><strong>{rupiah(po.total_amount)}</strong><span>{po.item_count} item</span></td><td data-label="Penerimaan"><strong>{po.quantity_received} / {po.quantity_ordered}</strong><span>unit</span></td><td data-label="Status"><Badge tone={statusTone(po.status)}>{statusText(po.status)}</Badge></td><td className={styles.mobileAction}><Link className={styles.detailLink} href={`/procurement/po/${po.id}`}>Buka detail</Link></td></tr>)}</tbody></table></div>:<div className={styles.empty}>Belum ada Purchase Order.</div>}</Card>

  <Card className={styles.panel}><div className={styles.panelHeader}><div><span className={styles.kicker}>RIWAYAT PR</span><h3>100 permintaan pembelian terakhir</h3></div><Badge>{purchaseRequests.length}</Badge></div>{purchaseRequests.length?<div className={`${styles.tableWrap} ${styles.mobileRegistry}`}><table><thead><tr><th>PR</th><th>Supplier</th><th>Estimasi</th><th>Status</th><th>Catatan</th></tr></thead><tbody>{purchaseRequests.map((pr)=><tr key={pr.id}><td data-label="PR"><strong>{pr.pr_number}</strong><span>{dateTime(pr.created_at)} · {pr.item_count} item</span></td><td data-label="Supplier"><strong>{pr.supplier_name||"—"}</strong></td><td data-label="Estimasi"><strong>{rupiah(pr.total_estimated_amount)}</strong></td><td data-label="Status"><Badge tone={statusTone(pr.status)}>{statusText(pr.status)}</Badge></td><td data-label="Catatan"><span>{pr.status==="REJECTED"?pr.rejection_reason:pr.notes||"—"}</span></td></tr>)}</tbody></table></div>:<div className={styles.empty}>Belum ada Permintaan Pembelian.</div>}</Card>
 </PageContainer>;
}
