import Link from "next/link";
import { redirect } from "next/navigation";
import { Alert } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { PageContainer, PageHeader } from "@/components/ui/page-layout";
import { PendingSubmitButton } from "@/components/pending-submit-button";
import { getAccessContext } from "@/lib/access/context";
import { getD1SchemaStatus } from "@/lib/d1/context";
import { listTreasuryAccounts } from "@/lib/d1/treasury";
import { createClient } from "@/lib/supabase/server";
import { createLoanRepaymentAction } from "./actions";
import styles from "../contracts/contracts.module.css";

export const dynamic="force-dynamic";
type PageProps={searchParams:Promise<{error?:string;status?:string}>};
type RepaymentRow={id:string;repayment_number:string;contract_id:string;member_id:string;status:string;channel:string;total_amount:number;principal_amount:number;interest_amount:number;penalty_amount:number;payment_reference:string;created_at:string;posted_at:string|null};
type ContractRow={id:string;contract_number:string;member_id:string;status:string;principal_amount:number;product_snapshot:Record<string,unknown>};
type ScheduleRow={contract_id:string;principal_amount:number;interest_amount:number;paid_principal_amount:number;paid_interest_amount:number;penalty_assessed_amount:number;paid_penalty_amount:number;penalty_waived_amount:number};
type MemberRow={id:string;member_number:string;full_name:string};
function money(value:unknown){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(value||0));}
function errorMessage(code?:string){const messages:Record<string,string>={invalid:"Data pembayaran belum lengkap atau nominal tidak valid.",d1:"D1 belum CURRENT sehingga kas/bank belum aman menerima angsuran.",treasury:"Kanal pembayaran tidak cocok dengan tipe treasury yang dipilih.",contract:"Kontrak harus berstatus DISBURSED untuk menerima angsuran.",pending:"Kontrak masih memiliki proses pembayaran yang belum selesai.",waiver:"Kontrak masih memiliki waiver denda yang belum selesai.",penalty:"Snapshot denda kedaluwarsa; batalkan draft dan buat ulang.",overpay:"Nominal pembayaran melebihi seluruh sisa kewajiban kontrak.",amount:"Nominal pembayaran tidak valid.",channel:"Kanal pembayaran tidak diizinkan.",snapshot:"Snapshot produk belum memuat kanal/event accounting pembayaran terbaru.",reference:"Referensi pembayaran harus 3–120 karakter.",forbidden:"Hak akses posting angsuran tidak tersedia.",save:"Pembayaran belum dapat disimpan."};return code?messages[code]||null:null;}
function snapshotChannels(value:unknown){const snapshot=value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};return Array.isArray(snapshot.repayment_channels)?snapshot.repayment_channels.map(String).filter(Boolean):[];}
function tone(status:string):"success"|"warning"|"danger"|"info"|"neutral"{if(status==="POSTED")return"success";if(status==="PROCESSING")return"info";if(status==="DRAFT")return"warning";if(status==="CANCELLED")return"danger";return"neutral";}

export default async function LoanRepaymentsPage({searchParams}:PageProps){
  const access=await getAccessContext();if(!access)redirect("/login");if(!access.permissions.includes("LOAN_REPAYMENT_VIEW"))redirect("/dashboard");
  const params=await searchParams;const canPost=access.permissions.includes("LOAN_REPAYMENT_POST");const schema=await getD1SchemaStatus();let treasuryAccounts:Awaited<ReturnType<typeof listTreasuryAccounts>>=[];
  if(schema.current&&schema.features.treasuryPeriod){try{treasuryAccounts=(await listTreasuryAccounts(access.organization.id)).filter(row=>row.status==="ACTIVE");}catch{treasuryAccounts=[];}}
  const supabase=await createClient();const [repaymentResult,contractResult,memberResult]=await Promise.all([
    supabase.from("loan_repayments").select("id,repayment_number,contract_id,member_id,status,channel,total_amount,principal_amount,interest_amount,penalty_amount,payment_reference,created_at,posted_at").eq("organization_id",access.organization.id).order("created_at",{ascending:false}).limit(200),
    supabase.from("loan_contracts").select("id,contract_number,member_id,status,principal_amount,product_snapshot").eq("organization_id",access.organization.id).eq("status","DISBURSED").order("created_at",{ascending:false}).limit(200),
    supabase.from("members").select("id,member_number,full_name").eq("organization_id",access.organization.id),
  ]);
  const repayments=(repaymentResult.data??[])as RepaymentRow[];const contracts=(contractResult.data??[])as ContractRow[];const members=(memberResult.data??[])as MemberRow[];const memberMap=new Map(members.map(member=>[member.id,member]));let schedule:ScheduleRow[]=[];
  if(contracts.length){const scheduleResult=await supabase.from("loan_installment_schedule").select("contract_id,principal_amount,interest_amount,paid_principal_amount,paid_interest_amount,penalty_assessed_amount,paid_penalty_amount,penalty_waived_amount").eq("organization_id",access.organization.id).in("contract_id",contracts.map(row=>row.id));schedule=(scheduleResult.data??[])as ScheduleRow[];}
  const outstandingMap=new Map<string,number>();const penaltyDueMap=new Map<string,number>();for(const row of schedule){const penaltyDue=Math.max(0,Number(row.penalty_assessed_amount||0)-Number(row.paid_penalty_amount||0)-Number(row.penalty_waived_amount||0));const outstanding=Math.max(0,Number(row.principal_amount||0)-Number(row.paid_principal_amount||0))+Math.max(0,Number(row.interest_amount||0)-Number(row.paid_interest_amount||0))+penaltyDue;outstandingMap.set(row.contract_id,(outstandingMap.get(row.contract_id)||0)+outstanding);penaltyDueMap.set(row.contract_id,(penaltyDueMap.get(row.contract_id)||0)+penaltyDue);}
  const pendingContracts=new Set(repayments.filter(row=>row.status==="DRAFT"||row.status==="PROCESSING").map(row=>row.contract_id));const availableContracts=contracts.filter(row=>(outstandingMap.get(row.id)||0)>0&&!pendingContracts.has(row.id));const failure=errorMessage(params.error)||(repaymentResult.error?"Schema angsuran belum tersedia.":null);

  return <PageContainer size="full">
    <PageHeader eyebrow="Simpan Pinjam · Pinjaman" title="Angsuran Masuk" description="Catat pembayaran pinjaman. Alokasi tetap mengikuti denda → bunga → pokok, periode tertua terlebih dahulu, lalu diposting ke D1 secara idempotent." actions={<div><Link className={styles.openLink} href="/simpan-pinjam">Beranda Simpan Pinjam</Link> <Link className={styles.openLink} href="/loans/penalties">Denda & Keringanan →</Link>{canPost?<details className={styles.create}><summary>+ Catat Pembayaran</summary>{availableContracts.length&&treasuryAccounts.length?<form action={createLoanRepaymentAction}><label>Kontrak aktif<select name="contract_id" required defaultValue=""><option value="" disabled>Pilih kontrak</option>{availableContracts.map(contract=>{const member=memberMap.get(contract.member_id);const channels=snapshotChannels(contract.product_snapshot);const penalty=penaltyDueMap.get(contract.id)||0;return <option key={contract.id} value={contract.id}>{contract.contract_number} · {member?.full_name||"Anggota"} · Sisa {money(outstandingMap.get(contract.id)||0)}{penalty?` · Denda ${money(penalty)}`:""} · {channels.join("/")||"snapshot lama"}</option>;})}</select></label><label>Nominal diterima<input type="number" name="amount" min="1" step="1" required/></label><label>Kanal<select name="channel" required defaultValue="CASH"><option value="CASH">CASH</option><option value="BANK_TRANSFER">BANK_TRANSFER</option><option value="QRIS">QRIS</option></select></label><label>Kas / Bank penerima<select name="treasury_account_id" required defaultValue=""><option value="" disabled>Pilih treasury</option>{treasuryAccounts.map(account=><option key={account.id} value={account.id}>{account.account_type} · {account.code} · {account.name}</option>)}</select></label><label>Referensi pembayaran<input name="payment_reference" required minLength={3} maxLength={120}/></label><label>Catatan<input name="request_note" maxLength={500}/></label><PendingSubmitButton pendingLabel="Menilai denda & menghitung alokasi…">Buat Draft Pembayaran</PendingSubmitButton></form>:<div className={styles.empty}><strong>Belum ada kontrak/sumber pembayaran yang siap.</strong></div>}</details>:null}</div>}/>
    {params.status?<Alert tone="success">Proses berhasil: {params.status.replace(/-/g," ")}.</Alert>:null}{failure?<Alert tone="danger">{failure}</Alert>:null}{!schema.current?<Alert tone="danger">D1 belum CURRENT. Posting angsuran diblok sampai schema D1 lengkap.</Alert>:null}
    <section className={styles.metrics}><Card density="compact"><span>Kontrak aktif</span><strong>{contracts.length}</strong><small>status DISBURSED</small></Card><Card density="compact"><span>Denda terutang</span><strong>{money(Array.from(penaltyDueMap.values()).reduce((a,b)=>a+b,0))}</strong><small>snapshot tersimpan</small></Card><Card density="compact"><span>Pembayaran posted</span><strong>{repayments.filter(row=>row.status==="POSTED").length}</strong><small>journal D1 tersedia</small></Card><Card density="compact"><span>Total diterima</span><strong>{money(repayments.filter(row=>row.status==="POSTED").reduce((sum,row)=>sum+Number(row.total_amount||0),0))}</strong><small>registry organisasi</small></Card></section>
    <Card className={styles.panel}><div className={styles.panelHead}><div><span>REGISTRY ANGSURAN</span><h3>Pembayaran dan alokasi</h3></div><Badge>{repayments.length}</Badge></div>{repayments.length?<>
      <div className={`${styles.tableWrap} ${styles.repaymentTableWrap}`}><table><thead><tr><th>No.</th><th>Anggota</th><th>Kanal</th><th>Nominal</th><th>Alokasi</th><th>Status</th><th></th></tr></thead><tbody>{repayments.map(row=>{const member=memberMap.get(row.member_id);return <tr key={row.id}><td><strong>{row.repayment_number}</strong><small>{new Date(row.posted_at||row.created_at).toLocaleString("id-ID",{timeZone:"Asia/Jakarta"})}</small></td><td><strong>{member?.full_name||"Anggota"}</strong><small>{member?.member_number||"—"}</small></td><td>{row.channel}</td><td><strong>{money(row.total_amount)}</strong><small>{row.payment_reference}</small></td><td><small>Denda {money(row.penalty_amount)}</small><small>Bunga {money(row.interest_amount)}</small><small>Pokok {money(row.principal_amount)}</small></td><td><Badge tone={tone(row.status)}>{row.status}</Badge></td><td><Link className={styles.openLink} href={`/loans/repayments/${row.id}`}>Buka</Link></td></tr>;})}</tbody></table></div>
      <div className={styles.mobileCards}>{repayments.map(row=>{const member=memberMap.get(row.member_id);return <article className={styles.paymentCard} key={row.id}><div className={styles.paymentHead}><div><strong>{member?.full_name||"Anggota"}</strong><small>{row.repayment_number}</small></div><Badge tone={tone(row.status)}>{row.status}</Badge></div><strong className={styles.paymentAmount}>{money(row.total_amount)}</strong><div className={styles.paymentMeta}><span>{row.channel}</span><span>Denda {money(row.penalty_amount)}</span><span>Bunga {money(row.interest_amount)}</span><span>Pokok {money(row.principal_amount)}</span></div><Link className={styles.mobileOpen} href={`/loans/repayments/${row.id}`}>Buka Detail →</Link></article>})}</div>
    </>:<div className={styles.empty}><strong>Belum ada pembayaran.</strong><p>Kontrak DISBURSED dapat menerima pembayaran sesuai snapshot produk.</p></div>}</Card>
    <Alert tone="info" title="Kontrol denda & alokasi">Denda hanya ditambah untuk hari yang belum pernah dinilai; partial payment menurunkan basis assessment berikutnya. Waiver harus selesai sebelum pembayaran baru dibuat.</Alert>
  </PageContainer>;
}
