import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Alert } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { PageContainer, PageHeader } from "@/components/ui/page-layout";
import { PendingSubmitButton } from "@/components/pending-submit-button";
import { getAccessContext } from "@/lib/access/context";
import { getD1SchemaStatus } from "@/lib/d1/context";
import { createClient } from "@/lib/supabase/server";
import { cancelLoanRepaymentAction, executeLoanRepaymentAction } from "../actions";
import styles from "../../contracts/contracts.module.css";

export const dynamic="force-dynamic";
type PageProps={params:Promise<{id:string}>;searchParams:Promise<{error?:string;status?:string;detail?:string}>};
type AllocationRow={id:string;installment_id:string;installment_number:number;principal_amount:number;interest_amount:number;penalty_amount:number};
type ScheduleRow={id:string;due_date:string;principal_amount:number;interest_amount:number;paid_principal_amount:number;paid_interest_amount:number;penalty_assessed_amount:number;paid_penalty_amount:number;penalty_waived_amount:number;status:string};
type EventRow={id:string;event_type:string;from_status:string|null;to_status:string;note:string|null;actor_user_id:string;created_at:string};
function money(value:unknown){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(value||0));}
function time(value:string|null){return value?new Date(value).toLocaleString("id-ID",{timeZone:"Asia/Jakarta",dateStyle:"medium",timeStyle:"short"}):"—";}
function errorMessage(code?:string,detail?:string){const messages:Record<string,string>={contract:"Kontrak tidak lagi aktif untuk pembayaran.",pending:"Masih ada proses pembayaran lain pada kontrak ini.",waiver:"Ada waiver denda yang belum selesai.",penalty:"Hari keterlambatan bertambah setelah draft dibuat. Batalkan dan buat ulang.",overpay:"Pembayaran melebihi sisa kewajiban.",amount:"Nominal pembayaran tidak valid.",channel:"Kanal pembayaran tidak valid.",snapshot:"Snapshot produk belum memuat konfigurasi pembayaran terbaru.",reference:"Referensi pembayaran tidak valid.",forbidden:"Hak akses posting pembayaran tidak tersedia.",payload:"Payload eksekusi pembayaran tidak konsisten.",d1:"D1 belum CURRENT.",stale:"Allocation snapshot tidak lagi cocok dengan saldo jadwal.",journal:"Journal D1 retry tidak sama dengan journal yang tersimpan.",save:"Proses pembayaran belum dapat diselesaikan."};if(code==="d1-post")return`Posting D1 belum selesai${detail?`: ${detail}`:"."} Retry aman karena idempotent.`;return code?messages[code]||"Proses pembayaran belum dapat diselesaikan.":null;}
function tone(status:string):"success"|"warning"|"danger"|"info"|"neutral"{if(status==="POSTED")return"success";if(status==="PROCESSING")return"info";if(status==="DRAFT")return"warning";if(status==="CANCELLED")return"danger";return"neutral";}

export default async function LoanRepaymentDetailPage({params,searchParams}:PageProps){
  const access=await getAccessContext();if(!access)redirect("/login");if(!access.permissions.includes("LOAN_REPAYMENT_VIEW"))redirect("/dashboard");
  const [{id},query,schema]=await Promise.all([params,searchParams,getD1SchemaStatus()]);const supabase=await createClient();const {data:row,error}=await supabase.from("loan_repayments").select("*").eq("id",id).eq("organization_id",access.organization.id).maybeSingle();if(error||!row)notFound();
  const [contractResult,memberResult,allocationResult,eventResult]=await Promise.all([supabase.from("loan_contracts").select("id,contract_number,status,principal_amount,total_interest_amount,total_installment_amount,first_due_date").eq("id",row.contract_id).eq("organization_id",access.organization.id).maybeSingle(),supabase.from("members").select("member_number,full_name").eq("id",row.member_id).eq("organization_id",access.organization.id).maybeSingle(),supabase.from("loan_repayment_allocations").select("id,installment_id,installment_number,principal_amount,interest_amount,penalty_amount").eq("repayment_id",id).eq("organization_id",access.organization.id).order("installment_number",{ascending:true}),supabase.from("loan_repayment_events").select("id,event_type,from_status,to_status,note,actor_user_id,created_at").eq("repayment_id",id).eq("organization_id",access.organization.id).order("created_at",{ascending:true})]);
  const contract=contractResult.data;const member=memberResult.data;const allocations=(allocationResult.data??[])as AllocationRow[];const events=(eventResult.data??[])as EventRow[];let schedule:ScheduleRow[]=[];if(contract){const scheduleResult=await supabase.from("loan_installment_schedule").select("id,due_date,principal_amount,interest_amount,paid_principal_amount,paid_interest_amount,penalty_assessed_amount,paid_penalty_amount,penalty_waived_amount,status").eq("contract_id",contract.id).eq("organization_id",access.organization.id).order("installment_number",{ascending:true});schedule=(scheduleResult.data??[])as ScheduleRow[];}
  const scheduleMap=new Map(schedule.map(item=>[item.id,item]));const outstanding=schedule.reduce((sum,item)=>sum+Math.max(0,Number(item.principal_amount)-Number(item.paid_principal_amount))+Math.max(0,Number(item.interest_amount)-Number(item.paid_interest_amount))+Math.max(0,Number(item.penalty_assessed_amount)-Number(item.paid_penalty_amount)-Number(item.penalty_waived_amount)),0);const penaltyDue=schedule.reduce((sum,item)=>sum+Math.max(0,Number(item.penalty_assessed_amount)-Number(item.paid_penalty_amount)-Number(item.penalty_waived_amount)),0);const canPost=access.permissions.includes("LOAN_REPAYMENT_POST");const failure=errorMessage(query.error,query.detail);

  return <PageContainer size="full">
    <PageHeader eyebrow="Simpan Pinjam · Detail Angsuran" title={row.repayment_number} description={`${contract?.contract_number||"Kontrak"} · ${member?.member_number||"—"} · ${member?.full_name||"Anggota"}`} actions={<Link href="/loans/repayments">← Daftar Angsuran</Link>}/>
    {query.status?<Alert tone="success">Proses berhasil: {query.status.replace(/-/g," ")}.</Alert>:null}{failure?<Alert tone="danger">{failure}</Alert>:null}
    <section className={styles.metrics}><Card density="compact"><span>Status</span><Badge tone={tone(row.status)}>{row.status}</Badge></Card><Card density="compact"><span>Pembayaran</span><strong>{money(row.total_amount)}</strong><small>{row.channel}</small></Card><Card density="compact"><span>Sisa kewajiban</span><strong>{money(outstanding)}</strong><small>denda {money(penaltyDue)}</small></Card><Card density="compact"><span>D1</span><strong>{schema.current?"CURRENT":"CHECK"}</strong><small>{row.d1_journal_entry_id?"journal tersedia":"belum posted"}</small></Card></section>
    <section className={styles.detailGrid}><Card className={styles.panel}><div className={styles.panelHead}><div><span>PAYMENT SNAPSHOT</span><h3>Nilai pembayaran</h3></div></div><dl className={styles.definition}><div><dt>Kontrak</dt><dd>{contract?.contract_number||"—"}</dd></div><div><dt>Status kontrak</dt><dd>{contract?.status||"—"}</dd></div><div><dt>Total</dt><dd>{money(row.total_amount)}</dd></div><div><dt>Referensi</dt><dd>{row.payment_reference}</dd></div><div><dt>Denda</dt><dd>{money(row.penalty_amount)}</dd></div><div><dt>Bunga</dt><dd>{money(row.interest_amount)}</dd></div><div><dt>Pokok</dt><dd>{money(row.principal_amount)}</dd></div><div><dt>Kanal</dt><dd>{row.channel}</dd></div><div><dt>Treasury D1</dt><dd>{row.treasury_account_id}</dd></div><div><dt>Sisa kewajiban kini</dt><dd>{money(outstanding)}</dd></div><div><dt>Denda terutang kini</dt><dd>{money(penaltyDue)}</dd></div><div className={styles.wide}><dt>Catatan</dt><dd>{row.request_note||"—"}</dd></div></dl></Card>
      <Card className={styles.panel}><div className={styles.panelHead}><div><span>EXECUTION</span><h3>D1 & idempotency</h3></div><Badge tone={schema.current?"success":"danger"}>{schema.current?"CURRENT":"BLOCKED"}</Badge></div><dl className={styles.definition}><div><dt>Idempotency</dt><dd>{row.idempotency_key}</dd></div><div><dt>Mulai proses</dt><dd>{time(row.execution_started_at)}</dd></div><div><dt>Posted</dt><dd>{time(row.posted_at)}</dd></div><div><dt>D1 Journal</dt><dd>{row.d1_journal_entry_id||"—"}</dd></div><div><dt>Policy alokasi</dt><dd>PENALTY → INTEREST → PRINCIPAL · oldest first</dd></div><div><dt>Event pokok</dt><dd>{row.principal_accounting_event_code}</dd></div><div><dt>Event bunga/denda</dt><dd>{row.interest_accounting_event_code} / {row.penalty_accounting_event_code}</dd></div></dl>{row.d1_journal_entry_id?<Link className={styles.openLink} href={`/finance/journals/${row.d1_journal_entry_id}`}>Buka jurnal D1 →</Link>:null}</Card></section>
    {row.status==="DRAFT"&&canPost?<Alert tone="warning" title="Allocation snapshot sudah dibekukan"><div className={styles.detailGrid}><form action={executeLoanRepaymentAction}><input type="hidden" name="repayment_id" value={row.id}/><input type="hidden" name="contract_id" value={row.contract_id}/><PendingSubmitButton pendingLabel="Memposting…">Post Pembayaran</PendingSubmitButton></form><form action={cancelLoanRepaymentAction}><input type="hidden" name="repayment_id" value={row.id}/><input type="hidden" name="contract_id" value={row.contract_id}/><input name="cancel_note" maxLength={500} placeholder="Catatan pembatalan (opsional)"/><PendingSubmitButton pendingLabel="Membatalkan…">Batalkan Draft</PendingSubmitButton></form></div></Alert>:null}
    {row.status==="PROCESSING"&&canPost?<Alert tone="info" title="Retry pembayaran aman"><form action={executeLoanRepaymentAction}><input type="hidden" name="repayment_id" value={row.id}/><input type="hidden" name="contract_id" value={row.contract_id}/><PendingSubmitButton pendingLabel="Merekonsiliasi…">Retry Pembayaran</PendingSubmitButton></form></Alert>:null}
    <Card className={styles.panel}><div className={styles.panelHead}><div><span>ALLOCATION SNAPSHOT</span><h3>Pembagian ke jadwal</h3></div><Badge>{allocations.length}</Badge></div>{allocations.length?<div className={styles.tableWrap}><table><thead><tr><th>Periode</th><th>Jatuh tempo</th><th>Denda</th><th>Bunga</th><th>Pokok</th><th>Status jadwal kini</th></tr></thead><tbody>{allocations.map(allocation=>{const item=scheduleMap.get(allocation.installment_id);return <tr key={allocation.id}><td><strong>#{allocation.installment_number}</strong></td><td>{item?.due_date||"—"}</td><td>{money(allocation.penalty_amount)}</td><td>{money(allocation.interest_amount)}</td><td>{money(allocation.principal_amount)}</td><td><Badge tone={item?.status==="PAID"?"success":"neutral"}>{item?.status||"—"}</Badge></td></tr>;})}</tbody></table></div>:<div className={styles.empty}>Allocation belum tersedia.</div>}</Card>
    <Card className={styles.panel}><div className={styles.panelHead}><div><span>AUDIT TRAIL</span><h3>Riwayat pembayaran</h3></div><Badge>{events.length}</Badge></div>{events.length?<div className={styles.tableWrap}><table><thead><tr><th>Waktu</th><th>Event</th><th>Transisi</th><th>Catatan</th><th>Aktor</th></tr></thead><tbody>{events.map(event=><tr key={event.id}><td>{time(event.created_at)}</td><td><strong>{event.event_type}</strong></td><td>{event.from_status||"—"} → {event.to_status}</td><td>{event.note||"—"}</td><td><small>{event.actor_user_id}</small></td></tr>)}</tbody></table></div>:<div className={styles.empty}>Belum ada event.</div>}</Card>
    <Alert tone="info" title="Kontrol repayment">Reversal pembayaran, waiver, koreksi, dan settlement tetap memakai transaksi koreksi terpisah; nominal posted tidak diedit langsung.</Alert>
  </PageContainer>;
}
