import Link from "next/link";
import { redirect } from "next/navigation";
import { getAccessContext } from "@/lib/access/context";
import { getD1SchemaStatus } from "@/lib/d1/context";
import { getApprovalQueue } from "@/lib/d1/approval-center";
import { createClient } from "@/lib/supabase/server";
import styles from "./approvals.module.css";

export const dynamic = "force-dynamic";

type QueueItem={key:string;category:string;reference:string;title:string;detail:string;amount:number|null;createdBy:string;createdAt:string;href:string};
function rupiah(value:number|null){if(value===null)return "—";return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(value);}
function waktu(value:string){return new Date(value).toLocaleString("id-ID",{timeZone:"Asia/Jakarta",dateStyle:"short",timeStyle:"short"});}
function categoryLabel(category:string){return ({PEMBELIAN:"Pembelian",HUTANG_SUPPLIER:"Hutang Pemasok",JURNAL:"Jurnal",ASET:"Aset Tetap",PENYUSUTAN:"Penyusutan",STOCK_OPNAME:"Hitung Stok",PRODUK_SIMPANAN:"Produk Simpanan",REKENING_SIMPANAN:"Rekening Simpanan",PRODUK_PINJAMAN:"Produk Pinjaman",PENGAJUAN_PINJAMAN:"Pengajuan Pinjaman",PENCAIRAN_PINJAMAN:"Pencairan Pinjaman",WAIVER_DENDA:"Waiver Denda",KOREKSI_ANGSURAN:"Koreksi Angsuran"} as Record<string,string>)[category]||category;}
function canReviewCategory(category:string,p:Set<string>){if(p.has("APPROVAL_VIEW"))return true;if(category==="PEMBELIAN")return p.has("PURCHASE_APPROVE");if(category==="HUTANG_SUPPLIER")return p.has("INVOICE_APPROVE");if(category==="JURNAL")return p.has("JOURNAL_APPROVE");if(category==="ASET"||category==="PENYUSUTAN")return p.has("ASSET_APPROVE");if(category==="STOCK_OPNAME")return p.has("ORG_MANAGE");if(category==="PRODUK_SIMPANAN")return p.has("SAVINGS_PRODUCT_APPROVE");if(category==="REKENING_SIMPANAN")return p.has("SAVINGS_ACCOUNT_APPROVE");if(category==="PRODUK_PINJAMAN")return p.has("LOAN_PRODUCT_APPROVE");if(category==="PENGAJUAN_PINJAMAN")return p.has("LOAN_APPLICATION_APPROVE");if(category==="PENCAIRAN_PINJAMAN")return p.has("LOAN_DISBURSEMENT_APPROVE");if(category==="WAIVER_DENDA")return p.has("LOAN_PENALTY_WAIVE_APPROVE");if(category==="KOREKSI_ANGSURAN")return p.has("LOAN_CORRECTION_APPROVE");return false;}

export default async function ApprovalCenterPage(){
  const access=await getAccessContext();if(!access)redirect("/login");
  const allowed=new Set(access.permissions);
  const canOpen=["APPROVAL_VIEW","PURCHASE_APPROVE","INVOICE_APPROVE","JOURNAL_APPROVE","ASSET_APPROVE","SAVINGS_PRODUCT_APPROVE","SAVINGS_ACCOUNT_APPROVE","LOAN_PRODUCT_APPROVE","LOAN_APPLICATION_APPROVE","LOAN_DISBURSEMENT_APPROVE","LOAN_PENALTY_WAIVE_APPROVE","LOAN_CORRECTION_APPROVE","ORG_MANAGE"].some(code=>allowed.has(code));
  if(!canOpen)redirect("/dashboard");
  const schema=await getD1SchemaStatus();if(!schema.features.assetDepreciation)redirect("/setup/database");
  const supabase=await createClient();
  const savingsProductTask=(allowed.has("SAVINGS_PRODUCT_APPROVE")||allowed.has("APPROVAL_VIEW"))
    ?supabase.from("savings_product_versions").select("id,product_id,version,display_name,created_by,created_at,submitted_at,savings_products!inner(id,code,organization_id)").eq("status","SUBMITTED").eq("savings_products.organization_id",access.organization.id).limit(80)
    :Promise.resolve({data:[],error:null});
  const savingsAccountTask=(allowed.has("SAVINGS_ACCOUNT_APPROVE")||allowed.has("APPROVAL_VIEW"))
    ?supabase.from("savings_accounts").select("id,account_number,rule_snapshot,opened_by,opened_at").eq("organization_id",access.organization.id).eq("status","PENDING").order("opened_at",{ascending:true}).limit(80)
    :Promise.resolve({data:[],error:null});
  const loanProductTask=(allowed.has("LOAN_PRODUCT_APPROVE")||allowed.has("APPROVAL_VIEW"))
    ?supabase.from("loan_product_versions").select("id,product_id,version,display_name,created_by,created_at,submitted_at,loan_products!inner(id,code,organization_id)").eq("status","SUBMITTED").eq("loan_products.organization_id",access.organization.id).limit(80)
    :Promise.resolve({data:[],error:null});
  const loanApplicationTask=(allowed.has("LOAN_APPLICATION_APPROVE")||allowed.has("APPROVAL_VIEW"))
    ?supabase.from("loan_applications").select("id,application_number,status,requested_principal_amount,requested_tenor_months,created_by,submitted_at,product_snapshot").eq("organization_id",access.organization.id).in("status",["SUBMITTED","UNDER_REVIEW"]).order("submitted_at",{ascending:true}).limit(80)
    :Promise.resolve({data:[],error:null});
  const loanDisbursementTask=(allowed.has("LOAN_DISBURSEMENT_APPROVE")||allowed.has("APPROVAL_VIEW"))
    ?supabase.from("loan_disbursements").select("id,disbursement_number,channel,recipient_name,net_disbursement_amount,created_by,created_at,submitted_at").eq("organization_id",access.organization.id).eq("status","SUBMITTED").order("submitted_at",{ascending:true}).limit(80)
    :Promise.resolve({data:[],error:null});
  const penaltyWaiverTask=(allowed.has("LOAN_PENALTY_WAIVE_APPROVE")||allowed.has("APPROVAL_VIEW"))
    ?supabase.from("loan_penalty_waivers").select("id,waiver_number,contract_id,requested_amount,reason,created_by,created_at,submitted_at").eq("organization_id",access.organization.id).eq("status","SUBMITTED").order("submitted_at",{ascending:true}).limit(80)
    :Promise.resolve({data:[],error:null});
  const correctionTask=(allowed.has("LOAN_CORRECTION_APPROVE")||allowed.has("APPROVAL_VIEW"))
    ?supabase.from("loan_repayment_reversals").select("id,reversal_number,repayment_id,reason,created_by,created_at,submitted_at").eq("organization_id",access.organization.id).eq("status","SUBMITTED").order("submitted_at",{ascending:true}).limit(80)
    :Promise.resolve({data:[],error:null});

  const [d1Queue,savingsProductResult,savingsAccountResult,loanProductResult,loanApplicationResult,loanDisbursementResult,penaltyWaiverResult,correctionResult]=await Promise.all([getApprovalQueue(access.organization.id),savingsProductTask,savingsAccountTask,loanProductTask,loanApplicationTask,loanDisbursementTask,penaltyWaiverTask,correctionTask]);
  const savingsProductQueue:QueueItem[]=(savingsProductResult.data??[]).map((row:any)=>{const product=Array.isArray(row.savings_products)?row.savings_products[0]:row.savings_products;return {key:`savings-product:${row.id}`,category:"PRODUK_SIMPANAN",reference:`${product?.code||"PRODUK"} · v${row.version}`,title:row.display_name,detail:"Versi aturan produk simpanan sudah diajukan dan menunggu pemeriksa yang berbeda.",amount:null,createdBy:row.created_by,createdAt:row.submitted_at||row.created_at,href:`/savings/products/${row.product_id}`};});
  const savingsAccountQueue:QueueItem[]=(savingsAccountResult.data??[]).map((row:any)=>{const snapshot=(row.rule_snapshot&&typeof row.rule_snapshot==="object")?row.rule_snapshot:{};const productName=String(snapshot.display_name||snapshot.product_code||"Produk Simpanan");return {key:`savings-account:${row.id}`,category:"REKENING_SIMPANAN",reference:row.account_number,title:productName,detail:"Permohonan pembukaan rekening simpanan menunggu pemeriksa yang berbeda sebelum dapat menerima transaksi.",amount:null,createdBy:row.opened_by,createdAt:row.opened_at,href:"/savings/accounts"};});
  const loanProductQueue:QueueItem[]=(loanProductResult.data??[]).map((row:any)=>{const product=Array.isArray(row.loan_products)?row.loan_products[0]:row.loan_products;return {key:`loan-product:${row.id}`,category:"PRODUK_PINJAMAN",reference:`${product?.code||"PRODUK"} · v${row.version}`,title:row.display_name,detail:"Versi aturan produk pinjaman sudah diajukan dan menunggu pemeriksa yang berbeda.",amount:null,createdBy:row.created_by,createdAt:row.submitted_at||row.created_at,href:`/loans/products/${row.product_id}`};});
  const loanApplicationQueue:QueueItem[]=(loanApplicationResult.data??[]).map((row:any)=>{const snapshot=(row.product_snapshot&&typeof row.product_snapshot==="object")?row.product_snapshot:{};return {key:`loan-application:${row.id}`,category:"PENGAJUAN_PINJAMAN",reference:row.application_number,title:String(snapshot.display_name||"Pengajuan Pinjaman"),detail:row.status==="UNDER_REVIEW"?"Pemeriksaan sudah dimulai dan menunggu keputusan checker.":"Pengajuan telah lulus eligibility gate dan menunggu checker yang berbeda.",amount:Number(row.requested_principal_amount||0),createdBy:row.created_by,createdAt:row.submitted_at,href:`/loans/applications/${row.id}`};});
  const loanDisbursementQueue:QueueItem[]=(loanDisbursementResult.data??[]).map((row:any)=>({key:`loan-disbursement:${row.id}`,category:"PENCAIRAN_PINJAMAN",reference:row.disbursement_number,title:`${row.channel} · ${row.recipient_name}`,detail:"Permintaan pencairan sudah diajukan. Checker harus memastikan sumber dana, tujuan, kanal, dan nominal sebelum menyetujui.",amount:Number(row.net_disbursement_amount||0),createdBy:row.created_by,createdAt:row.submitted_at||row.created_at,href:`/loans/disbursements/${row.id}`}));
  const penaltyWaiverQueue:QueueItem[]=(penaltyWaiverResult.data??[]).map((row:any)=>({key:`penalty-waiver:${row.id}`,category:"WAIVER_DENDA",reference:row.waiver_number,title:"Permohonan pembebasan denda pinjaman",detail:String(row.reason||"Waiver denda menunggu checker berbeda."),amount:Number(row.requested_amount||0),createdBy:row.created_by,createdAt:row.submitted_at||row.created_at,href:`/loans/penalties#waiver-${row.id}`}));
  const correctionQueue:QueueItem[]=(correctionResult.data??[]).map((row:any)=>({key:`loan-correction:${row.id}`,category:"KOREKSI_ANGSURAN",reference:row.reversal_number,title:"Permohonan reversal angsuran posted",detail:String(row.reason||"Koreksi pembayaran menunggu checker berbeda."),amount:null,createdBy:row.created_by,createdAt:row.submitted_at||row.created_at,href:"/loans/corrections"}));
  const allQueue:QueueItem[]=[...(d1Queue as QueueItem[]),...savingsProductQueue,...savingsAccountQueue,...loanProductQueue,...loanApplicationQueue,...loanDisbursementQueue,...penaltyWaiverQueue,...correctionQueue].sort((a,b)=>a.createdAt.localeCompare(b.createdAt));
  const queue=allQueue.filter(item=>canReviewCategory(item.category,allowed));
  const mine=queue.filter(item=>item.createdBy===access.user.id).length,reviewable=queue.filter(item=>item.createdBy!==access.user.id).length;
  const categories=new Map<string,number>();for(const item of queue)categories.set(item.category,(categories.get(item.category)||0)+1);

  return <main className={styles.page}><header className={styles.topbar}><div><p>KONTROL · PEMERIKSAAN</p><h1>Pusat Persetujuan</h1></div><nav><Link href="/dashboard">Dashboard</Link></nav></header><div className={styles.content}>
    <section className={styles.hero}><div><span>PEKERJAAN YANG MENUNGGU PEMERIKSAAN</span><h2>Lihat apa yang perlu diperiksa, lalu buka detail sebelum memberi keputusan.</h2><p>Halaman ini menjadi pusat antrian. Keputusan tetap dilakukan di halaman asal agar data lengkap terlihat terlebih dahulu. Pembuat tidak boleh menyetujui pekerjaannya sendiri.</p></div><div className={styles.role}><span>Role aktif</span><strong>{access.role.name}</strong><small>{access.organization.name}</small></div></section>
    <section className={styles.metrics}><article><span>Total menunggu</span><strong>{queue.length}</strong><small>sesuai hak akses Anda</small></article><article className={reviewable?styles.attention:undefined}><span>Siap Anda periksa</span><strong>{reviewable}</strong><small>dibuat pengguna lain</small></article><article><span>Dibuat oleh Anda</span><strong>{mine}</strong><small>harus diperiksa orang lain</small></article><article><span>Jenis pekerjaan</span><strong>{categories.size}</strong><small>kategori yang tampil</small></article></section>
    {categories.size?<section className={styles.categoryStrip}>{Array.from(categories.entries()).map(([category,count])=><div key={category}><span>{categoryLabel(category)}</span><strong>{count}</strong></div>)}</section>:null}
    <section className={styles.panel}><div className={styles.panelHeader}><div><span>ANTRIAN PEMERIKSAAN</span><h3>Yang perlu ditindaklanjuti</h3></div><b>{queue.length}</b></div>{queue.length?<div className={styles.queue}>{queue.map(item=>{const own=item.createdBy===access.user.id;return <article key={item.key} className={own?styles.own:styles.reviewable}><div className={styles.queueTop}><span>{categoryLabel(item.category)}</span><b>{own?"MENUNGGU ORANG LAIN":"SIAP DIPERIKSA"}</b></div><h4>{item.reference}</h4><strong>{item.title}</strong><p>{item.detail}</p><div className={styles.queueMeta}><span>{rupiah(item.amount)}</span><span>{waktu(item.createdAt)}</span></div><Link href={item.href}>{own?"Lihat status →":"Buka detail & periksa →"}</Link></article>;})}</div>:<div className={styles.empty}><strong>Tidak ada pekerjaan yang menunggu.</strong><p>Semua proses yang menjadi kewenangan Anda sudah selesai atau belum ada yang dikirim untuk diperiksa.</p></div>}</section>
    <section className={styles.notice}><strong>Kenapa tidak ada tombol “Setujui Semua”?</strong><p>Karena setiap keputusan membutuhkan konteks. Produk, rekening, pengajuan/pencairan pinjaman, waiver denda, dan reversal angsuran harus dibuka serta diperiksa sebelum disetujui.</p></section>
  </div></main>;
}
