import Link from "next/link";
import { redirect } from "next/navigation";
import { PendingSubmitButton } from "@/components/pending-submit-button";
import { getAccessContext } from "@/lib/access/context";
import { getD1SchemaStatus } from "@/lib/d1/context";
import { listTreasuryAccounts } from "@/lib/d1/treasury";
import { createClient } from "@/lib/supabase/server";
import { cancelRepaymentReversalAction, createFullSettlementAction, createRepaymentReversalAction, decideRepaymentReversalAction, executeRepaymentReversalAction, submitRepaymentReversalAction } from "./actions";
import styles from "../contracts/contracts.module.css";

export const dynamic="force-dynamic";
type Props={searchParams:Promise<{error?:string;status?:string;detail?:string}>};
type Repayment={id:string;repayment_number:string;contract_id:string;member_id:string;total_amount:number;posted_at:string|null;d1_journal_entry_id:string|null;treasury_account_id:string;status:string};
type Reversal={id:string;reversal_number:string;repayment_id:string;contract_id:string;member_id:string;status:string;reason:string;created_by:string;created_at:string;original_d1_journal_entry_id:string;reversal_d1_journal_entry_id:string|null};
type Contract={id:string;contract_number:string;member_id:string;status:string};
type Member={id:string;member_number:string;full_name:string};
type Schedule={contract_id:string;principal_amount:number;interest_amount:number;paid_principal_amount:number;paid_interest_amount:number;penalty_assessed_amount:number;paid_penalty_amount:number;penalty_waived_amount:number};
function money(v:unknown){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));}
function message(code?:string,detail?:string){const m:Record<string,string>={invalid:"Data belum lengkap.",stale:"Reversal diblok karena setelah pembayaran ini sudah ada transaksi/denda/waiver berikutnya.",exists:"Pembayaran ini sudah memiliki proses reversal aktif/final.",maker:"Maker tidak boleh menyetujui reversal sendiri.",pending:"Masih ada proses pembayaran/waiver/koreksi yang belum selesai.",forbidden:"Hak akses tidak tersedia.",nothing:"Kontrak sudah tidak memiliki kewajiban.",contract:"Kontrak/pembayaran tidak lagi memenuhi syarat.",reason:"Alasan reversal minimal 8 karakter.",journal:"Jurnal retry tidak sama dengan jurnal reversal sebelumnya.",d1:"D1 belum CURRENT.",treasury:"Kas/Bank tidak cocok dengan kanal pembayaran.",payload:"Payload reversal tidak konsisten.",save:"Proses belum dapat diselesaikan."};if(code==="d1-post")return`Posting reversal D1 gagal${detail?`: ${detail}`:"."} Retry tetap aman.`;return code?m[code]||m.save:null;}

export default async function CorrectionsPage({searchParams}:Props){
 const access=await getAccessContext();if(!access)redirect("/login");const allowed=new Set(access.permissions);if(!allowed.has("LOAN_CORRECTION_VIEW")&&!allowed.has("LOAN_REPAYMENT_POST"))redirect("/dashboard");const params=await searchParams;const schema=await getD1SchemaStatus();
 let treasury:Awaited<ReturnType<typeof listTreasuryAccounts>>=[];if(schema.current&&schema.features.treasuryPeriod){try{treasury=(await listTreasuryAccounts(access.organization.id)).filter(x=>x.status==="ACTIVE");}catch{treasury=[];}}
 const supabase=await createClient();
 const [repaymentsResult,reversalsResult,contractsResult,membersResult,scheduleResult]=await Promise.all([
  supabase.from("loan_repayments").select("id,repayment_number,contract_id,member_id,total_amount,posted_at,d1_journal_entry_id,treasury_account_id,status").eq("organization_id",access.organization.id).eq("status","POSTED").order("posted_at",{ascending:false}).limit(200),
  supabase.from("loan_repayment_reversals").select("id,reversal_number,repayment_id,contract_id,member_id,status,reason,created_by,created_at,original_d1_journal_entry_id,reversal_d1_journal_entry_id").eq("organization_id",access.organization.id).order("created_at",{ascending:false}).limit(200),
  supabase.from("loan_contracts").select("id,contract_number,member_id,status").eq("organization_id",access.organization.id).eq("status","DISBURSED").order("created_at",{ascending:false}).limit(200),
  supabase.from("members").select("id,member_number,full_name").eq("organization_id",access.organization.id),
  supabase.from("loan_installment_schedule").select("contract_id,principal_amount,interest_amount,paid_principal_amount,paid_interest_amount,penalty_assessed_amount,paid_penalty_amount,penalty_waived_amount").eq("organization_id",access.organization.id),
 ]);
 const repayments=(repaymentsResult.data??[]) as Repayment[],reversals=(reversalsResult.data??[]) as Reversal[],contracts=(contractsResult.data??[]) as Contract[],members=(membersResult.data??[]) as Member[],schedule=(scheduleResult.data??[]) as Schedule[];const memberMap=new Map(members.map(x=>[x.id,x]));const reversalRepayments=new Set(reversals.filter(x=>["DRAFT","SUBMITTED","APPROVED","PROCESSING","REVERSED"].includes(x.status)).map(x=>x.repayment_id));const eligible=repayments.filter(x=>x.d1_journal_entry_id&&!reversalRepayments.has(x.id));const dueMap=new Map<string,number>();for(const s of schedule){const due=Math.max(0,Number(s.principal_amount)-Number(s.paid_principal_amount))+Math.max(0,Number(s.interest_amount)-Number(s.paid_interest_amount))+Math.max(0,Number(s.penalty_assessed_amount)-Number(s.paid_penalty_amount)-Number(s.penalty_waived_amount));dueMap.set(s.contract_id,(dueMap.get(s.contract_id)||0)+due);}
 const canRequest=allowed.has("LOAN_CORRECTION_REQUEST"),canApprove=allowed.has("LOAN_CORRECTION_APPROVE"),canExecute=allowed.has("LOAN_CORRECTION_EXECUTE"),canSettle=allowed.has("LOAN_REPAYMENT_POST");const failure=message(params.error,params.detail)||(reversalsResult.error?"Schema koreksi 4E-5C belum tersedia.":null);
 return <section className="workspace"><header className="workspace-header"><div><p className="workspace-kicker">SIMPAN PINJAM · KOREKSI</p><h1>Koreksi & Pelunasan</h1></div></header><div className={`workspace-content ${styles.content}`}>
  <section className={styles.hero}><div><span>PHASE 4E-5C</span><h2>Reversal tidak menghapus transaksi lama; sistem membuat jurnal kebalikan dan memulihkan jadwal setelah checker menyetujui.</h2><p>Pelunasan penuh memakai seluruh kewajiban kontraktual yang masih tersisa. Tidak ada rebate bunga otomatis karena kebijakan rebate belum dikonfigurasi.</p></div></section>
  {params.status?<div className={styles.success}>Berhasil: {params.status.replace(/-/g," ")}.</div>:null}{failure?<div className={styles.error}>{failure}</div>:null}{!schema.current?<div className={styles.error}>D1 belum CURRENT; reversal dan settlement diblok.</div>:null}
  <section className={styles.metrics}><article><span>Reversal</span><strong>{reversals.length}</strong><small>audit append-only</small></article><article><span>Menunggu approval</span><strong>{reversals.filter(x=>x.status==="SUBMITTED").length}</strong><small>maker-checker</small></article><article><span>Siap eksekusi</span><strong>{reversals.filter(x=>x.status==="APPROVED"||x.status==="PROCESSING").length}</strong><small>D1 idempotent</small></article><article><span>Kontrak aktif</span><strong>{contracts.length}</strong><small>siap settlement</small></article></section>
  <section className={styles.detailGrid}>
   <article className={styles.panel}><div className={styles.panelHead}><div><span>REVERSAL</span><h3>Ajukan koreksi pembayaran</h3></div></div>{canRequest&&eligible.length?<form action={createRepaymentReversalAction}><label>Pembayaran posted<select name="repayment_id" required defaultValue=""><option value="" disabled>Pilih pembayaran</option>{eligible.map(r=>{const m=memberMap.get(r.member_id);return <option key={r.id} value={r.id}>{r.repayment_number} · {m?.full_name||"Anggota"} · {money(r.total_amount)}</option>;})}</select></label><label>Alasan koreksi<textarea name="reason" required minLength={8} maxLength={500} placeholder="Jelaskan kesalahan transaksi dan alasan reversal"/></label><PendingSubmitButton pendingLabel="Membuat…">Buat Draft Reversal</PendingSubmitButton></form>:<div className={styles.empty}><strong>Tidak ada pembayaran yang dapat diajukan.</strong><p>Hanya pembayaran POSTED yang tidak memiliki reversal aktif/final. Reversal REJECTED/CANCELLED boleh diajukan ulang.</p></div>}</article>
   <article className={styles.panel}><div className={styles.panelHead}><div><span>FULL SETTLEMENT</span><h3>Pelunasan penuh kontraktual</h3></div></div>{canSettle&&contracts.length&&treasury.length?<form action={createFullSettlementAction}><label>Kontrak<select name="contract_id" required defaultValue=""><option value="" disabled>Pilih kontrak</option>{contracts.filter(c=>(dueMap.get(c.id)||0)>0).map(c=>{const m=memberMap.get(c.member_id);return <option key={c.id} value={c.id}>{c.contract_number} · {m?.full_name||"Anggota"} · estimasi {money(dueMap.get(c.id)||0)}</option>;})}</select></label><label>Kanal<select name="channel" defaultValue="CASH"><option>CASH</option><option>BANK_TRANSFER</option><option>QRIS</option></select></label><label>Kas / Bank<select name="treasury_account_id" required defaultValue=""><option value="" disabled>Pilih treasury</option>{treasury.map(t=><option key={t.id} value={t.id}>{t.account_type} · {t.code} · {t.name}</option>)}</select></label><label>Referensi<input name="reference" required minLength={3} maxLength={120}/></label><label>Catatan<input name="note" maxLength={500}/></label><p className={styles.formNote}>Nominal final dihitung ulang server-side termasuk denda terbaru. Kebijakan: CONTRACTUAL_OUTSTANDING_NO_INTEREST_REBATE.</p><PendingSubmitButton pendingLabel="Menghitung…">Buat Draft Pelunasan</PendingSubmitButton></form>:<div className={styles.empty}>Belum ada kontrak/treasury yang siap.</div>}</article>
  </section>
  <section className={styles.panel}><div className={styles.panelHead}><div><span>REGISTRY KOREKSI</span><h3>Maker → checker → D1 reversal</h3></div><b>{reversals.length}</b></div>{reversals.length?<div className={styles.tableWrap}><table><thead><tr><th>No.</th><th>Pembayaran</th><th>Alasan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{reversals.map(r=>{const payment=repayments.find(x=>x.id===r.repayment_id);const own=r.created_by===access.user.id;return <tr key={r.id}><td><strong>{r.reversal_number}</strong><small>{new Date(r.created_at).toLocaleString("id-ID",{timeZone:"Asia/Jakarta"})}</small></td><td><strong>{payment?.repayment_number||r.repayment_id}</strong><small>{payment?money(payment.total_amount):"—"}</small></td><td>{r.reason}</td><td><span className={styles.badge}>{r.status}</span>{r.reversal_d1_journal_entry_id?<Link href={`/finance/journals/${r.reversal_d1_journal_entry_id}`}>Jurnal reversal</Link>:null}</td><td>{r.status==="DRAFT"&&own&&canRequest?<><form action={submitRepaymentReversalAction}><input type="hidden" name="reversal_id" value={r.id}/><PendingSubmitButton pendingLabel="Mengirim…">Submit</PendingSubmitButton></form><form action={cancelRepaymentReversalAction}><input type="hidden" name="reversal_id" value={r.id}/><PendingSubmitButton pendingLabel="Batal…">Batalkan</PendingSubmitButton></form></>:null}{r.status==="SUBMITTED"&&!own&&canApprove?<><form action={decideRepaymentReversalAction}><input type="hidden" name="reversal_id" value={r.id}/><input type="hidden" name="decision" value="APPROVE"/><PendingSubmitButton pendingLabel="Menyetujui…">Approve</PendingSubmitButton></form><form action={decideRepaymentReversalAction}><input type="hidden" name="reversal_id" value={r.id}/><input type="hidden" name="decision" value="REJECT"/><PendingSubmitButton pendingLabel="Menolak…">Reject</PendingSubmitButton></form></>:null}{(r.status==="APPROVED"||r.status==="PROCESSING")&&canExecute?<form action={executeRepaymentReversalAction}><input type="hidden" name="reversal_id" value={r.id}/><PendingSubmitButton pendingLabel="Memposting…">{r.status==="PROCESSING"?"Retry":"Eksekusi"}</PendingSubmitButton></form>:null}</td></tr>;})}</tbody></table></div>:<div className={styles.empty}>Belum ada reversal.</div>}</section>
  <section className={styles.notice}><strong>Guardrail fase ini</strong><p>Reversal hanya untuk transaksi terbaru yang belum diikuti repayment, assessment denda, atau waiver berikutnya. Restrukturisasi, reschedule, rebate bunga, dan write-off tidak dilakukan lewat edit jadwal; modul khususnya ditahan sampai accounting/reconciliation berikutnya.</p></section>
 </div></section>;
}
