"use client";
import type { ReactNode } from "react";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { usePathname,useRouter } from "next/navigation";
import { LogoutButton } from "@/components/logout-button";
import { KopdesKuBrand } from "@/components/brand/kopdesku-brand";
import { Drawer } from "@/components/ui/overlays";
import { ChevronLeftIcon,FinanceIcon,HomeIcon,InventoryIcon,MoreIcon,PosIcon,ReportIcon,SettingsIcon,TransactionIcon,UsersIcon,type IconProps } from "@/components/ui/icons";

type ShellAccess={profile:{fullName:string};role:{name:string};permissions:string[]};
type IconComponent=(props:IconProps)=>ReactNode;
type NavItem={label:string;href:string;permission?:string;anyPermissions?:string[];badge?:string;icon?:IconComponent};
const groups:Array<{section:string;items:NavItem[]}>= [
 {section:"Utama",items:[{label:"Dashboard",href:"/dashboard",permission:"DASHBOARD_VIEW",icon:HomeIcon},{label:"POS / Kasir",href:"/pos",permission:"POS_ACCESS",icon:PosIcon},{label:"Kasir / Shift",href:"/teller",permission:"POS_ACCESS",icon:TransactionIcon}]},
 {section:"Operasional",items:[{label:"Anggota",href:"/members",permission:"MEMBER_VIEW",icon:UsersIcon},{label:"Stok & Gudang",href:"/inventory",permission:"INVENTORY_VIEW",icon:InventoryIcon},{label:"Pembelian",href:"/procurement",permission:"PURCHASE_VIEW",icon:TransactionIcon},{label:"Hutang Pemasok",href:"/procurement/ap",permission:"AP_VIEW",icon:FinanceIcon}]},
 {section:"Keuangan",items:[{label:"Ringkasan Keuangan",href:"/finance",permission:"FINANCE_VIEW",icon:FinanceIcon},{label:"Kas & Bank",href:"/finance/treasury",permission:"FINANCE_VIEW"},{label:"Jurnal",href:"/finance/journals",permission:"FINANCE_VIEW"},{label:"Aset Tetap",href:"/finance/assets",permission:"FINANCE_VIEW"},{label:"Kesiapan Tutup Buku",href:"/finance/closing-readiness",permission:"FINANCE_VIEW"},{label:"Pengaturan Akuntansi",href:"/finance/settings",anyPermissions:["ACCOUNTING_MANAGE","ACCOUNTING_APPROVE"],icon:SettingsIcon}]},
 {section:"Simpan Pinjam",items:[{label:"Produk Simpanan",href:"/savings/products",permission:"SAVINGS_PRODUCT_VIEW",badge:"Config"},{label:"Rekening Simpanan",href:"/savings/accounts",permission:"SAVINGS_ACCOUNT_VIEW"},{label:"Laporan & Integritas",href:"/savings/reports",anyPermissions:["SAVINGS_ACCOUNT_VIEW","SAVINGS_TRANSACTION_VIEW"],icon:ReportIcon},{label:"Produk Pinjaman",href:"/loans/products",permission:"LOAN_PRODUCT_VIEW",badge:"Config"},{label:"Pengajuan Pinjaman",href:"/loans/applications",permission:"LOAN_APPLICATION_VIEW"},{label:"Kontrak & Jadwal",href:"/loans/contracts",permission:"LOAN_CONTRACT_VIEW"},{label:"Pencairan Pinjaman",href:"/loans/disbursements",permission:"LOAN_DISBURSEMENT_VIEW"},{label:"Angsuran Pinjaman",href:"/loans/repayments",permission:"LOAN_REPAYMENT_VIEW"},{label:"Denda & Waiver",href:"/loans/penalties",permission:"LOAN_PENALTY_VIEW"},{label:"Koreksi & Pelunasan",href:"/loans/corrections",anyPermissions:["LOAN_CORRECTION_VIEW","LOAN_REPAYMENT_POST"]},{label:"Accounting & Rekonsiliasi",href:"/loans/reports",permission:"LOAN_REPORT_VIEW",icon:ReportIcon}]},
 {section:"Kontrol",items:[{label:"Pusat Persetujuan",href:"/approvals",anyPermissions:["APPROVAL_VIEW","PURCHASE_APPROVE","INVOICE_APPROVE","JOURNAL_APPROVE","ASSET_APPROVE","SAVINGS_PRODUCT_APPROVE","SAVINGS_ACCOUNT_APPROVE","LOAN_PRODUCT_APPROVE","LOAN_APPLICATION_APPROVE","LOAN_DISBURSEMENT_APPROVE","LOAN_PENALTY_WAIVE_APPROVE","LOAN_CORRECTION_APPROVE","ORG_MANAGE"]},{label:"Laporan Penjualan",href:"/reports/daily-sales",permission:"REPORT_VIEW",icon:ReportIcon},{label:"Kesiapan Rilis",href:"/readiness",permission:"ORG_MANAGE",badge:"Go-Live"},{label:"Kapasitas Sistem",href:"/capacity",permission:"ORG_MANAGE",badge:"Zero Cost"},{label:"Backup & Pemulihan",href:"/capacity/recovery",permission:"ORG_MANAGE"},{label:"Pengaturan Database",href:"/setup/database",permission:"ORG_MANAGE",badge:"System",icon:SettingsIcon}]}
];
const noShell=new Set(["/","/login"]);
function allowed(item:NavItem,permissions:Set<string>){if(item.permission&&!permissions.has(item.permission))return false;if(item.anyPermissions?.length&&!item.anyPermissions.some(code=>permissions.has(code)))return false;return true}
function firstAllowed(items:NavItem[],permissions:Set<string>,fallback="/dashboard"){return items.find(i=>allowed(i,permissions))?.href||fallback}
export function AppNavigationShellV2({access,children}:{access:ShellAccess;children:ReactNode}){
 const pathname=usePathname(),router=useRouter();const [pendingHref,setPendingHref]=useState<string|null>(null),[navigationPending,setNavigationPending]=useState(false),[moreOpen,setMoreOpen]=useState(false);
 const permissions=useMemo(()=>new Set(access.permissions),[access.permissions]);const visibleGroups=useMemo(()=>groups.map(g=>({...g,items:g.items.filter(i=>allowed(i,permissions))})).filter(g=>g.items.length),[permissions]);const allItems=visibleGroups.flatMap(g=>g.items);
 const active=allItems.filter(i=>pathname===i.href||pathname.startsWith(`${i.href}/`)).sort((a,b)=>b.href.length-a.href.length)[0],displayedActiveHref=pendingHref||active?.href,firstName=access.profile.fullName.trim().split(/\s+/)[0]||"U";
 const transactionHref=firstAllowed([{label:"Kasir / Shift",href:"/teller",permission:"POS_ACCESS"},{label:"Rekening Simpanan",href:"/savings/accounts",permission:"SAVINGS_ACCOUNT_VIEW"},{label:"Pembelian",href:"/procurement",permission:"PURCHASE_VIEW"}],permissions);
 const reportHref=firstAllowed([{label:"Laporan Penjualan",href:"/reports/daily-sales",permission:"REPORT_VIEW"},{label:"Laporan Simpanan",href:"/savings/reports",anyPermissions:["SAVINGS_ACCOUNT_VIEW","SAVINGS_TRANSACTION_VIEW"]},{label:"Laporan Pinjaman",href:"/loans/reports",permission:"LOAN_REPORT_VIEW"},{label:"Keuangan",href:"/finance",permission:"FINANCE_VIEW"}],permissions);
 useEffect(()=>{setPendingHref(null);setNavigationPending(false);setMoreOpen(false)},[pathname]);useEffect(()=>{if(!navigationPending)return;const t=window.setTimeout(()=>{setPendingHref(null);setNavigationPending(false)},8000);return()=>window.clearTimeout(t)},[navigationPending]);
 function warmRoute(href:string){if(href!==pathname)router.prefetch(href)}function beginNavigation(href?:string){if(href&&href===pathname)return;if(href){setPendingHref(href);router.prefetch(href)}setNavigationPending(true)}function back(){beginNavigation();if(window.history.length>1)router.back();else router.push("/dashboard")}
 if(noShell.has(pathname))return <>{children}</>;
 const mobile=[{label:"Beranda",href:"/dashboard",Icon:HomeIcon},{label:"POS",href:permissions.has("POS_ACCESS")?"/pos":"/dashboard",Icon:PosIcon},{label:"Transaksi",href:transactionHref,Icon:TransactionIcon},{label:"Laporan",href:reportHref,Icon:ReportIcon}];
 return <div className={`app-shell kdk-app-shell ${navigationPending?"shell-is-navigating":""}`}><aside className="desktop-sidebar kdk-sidebar"><Link href="/dashboard" className="sidebar-brand persistent-brand" aria-label="Buka Dashboard" onClick={()=>beginNavigation("/dashboard")}><KopdesKuBrand compact inverse markOnly/><span className="sidebar-brand-copy"><strong>KopdesKu</strong><small>KDKMP Kedungharjo</small></span></Link><button type="button" className="sidebar-back-button" onClick={back}><ChevronLeftIcon size={18}/><span>Kembali</span></button><nav className="sidebar-nav" aria-label="Navigasi utama">{visibleGroups.map(group=><section className="nav-group" key={group.section}><p>{group.section}</p>{group.items.map(item=>{const Icon=item.icon,isPending=pendingHref===item.href;return <Link href={item.href} prefetch className={`nav-item ${displayedActiveHref===item.href?"active":""} ${isPending?"pending":""}`} key={`${group.section}-${item.label}`} onPointerEnter={()=>warmRoute(item.href)} onFocus={()=>warmRoute(item.href)} onClick={()=>beginNavigation(item.href)}>{Icon?<Icon size={18}/>:<span className="nav-icon-placeholder"/>}<span className="nav-label">{item.label}</span>{isPending?<small>Membuka…</small>:item.badge?<small>{item.badge}</small>:null}</Link>})}</section>)}</nav><div className="sidebar-profile"><div className="avatar">{firstName.slice(0,1).toUpperCase()}</div><div className="profile-copy"><strong>{access.profile.fullName}</strong><span>{access.role.name}</span></div><LogoutButton/></div></aside><main className="kdk-shell-main"><header className="kdk-topbar"><button type="button" className="kdk-mobile-back" onClick={back} aria-label="Kembali"><ChevronLeftIcon/></button><div className="kdk-topbar-context"><span>KopdesKu</span><strong>{active?.label||"Workspace"}</strong></div><div className="kdk-topbar-user"><span>{access.role.name}</span><strong>{firstName}</strong></div></header><div className="persistent-content">{children}</div></main><nav className="mobile-bottom-nav kdk-mobile-nav" aria-label="Navigasi mobile">{mobile.map(({label,href,Icon})=><Link key={label} href={href} className={(pathname===href||pathname.startsWith(`${href}/`))?"active":""} onClick={()=>beginNavigation(href)}><Icon size={20}/><span>{label}</span></Link>)}<button type="button" className={moreOpen?"active":""} onClick={()=>setMoreOpen(true)}><MoreIcon size={20}/><span>Lainnya</span></button></nav><Drawer open={moreOpen} title="Menu lainnya" onClose={()=>setMoreOpen(false)}>{visibleGroups.map(group=><section className="kdk-more-group" key={group.section}><h3>{group.section}</h3>{group.items.map(item=>{const Icon=item.icon;return <Link key={item.href} href={item.href} onClick={()=>beginNavigation(item.href)}>{Icon?<Icon size={18}/>:<MoreIcon size={18}/>}<span>{item.label}</span></Link>})}</section>)}</Drawer></div>
}
