import Link from "next/link";
import { redirect } from "next/navigation";
import { Alert } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { PageContainer, PageHeader } from "@/components/ui/page-layout";
import { getAccessContext } from "@/lib/access/context";
import { getD1SchemaStatus } from "@/lib/d1/context";
import { getLoanAccountingSnapshot, type LoanAccountingJournalRow } from "@/lib/d1/loan-reconciliation";
import { createClient } from "@/lib/supabase/server";
import styles from "../contracts/contracts.module.css";

export const dynamic="force-dynamic";
type ContractRow={id:string;contract_number:string;status:string;principal_amount:number;first_due_date:string};
type ScheduleRow={contract_id:string;installment_number:number;due_date:string;principal_amount:number;interest_amount:number;paid_principal_amount:number;paid_interest_amount:number;penalty_assessed_amount:number;paid_penalty_amount:number;penalty_waived_amount:number;status:string};
type DisbursementRow={id:string;contract_id:string;status:string;net_disbursement_amount:number;d1_journal_entry_id:string|null;disbursed_at:string|null};
type RepaymentRow={id:string;contract_id:string;status:string;principal_amount:number;interest_amount:number;penalty_amount:number;d1_journal_entry_id:string|null;posted_at:string|null};
type ReversalRow={id:string;repayment_id:string;contract_id:string;status:string;reversal_d1_journal_entry_id:string|null;reversed_at:string|null};
type AgingRow={contractId:string;contractNumber:string;status:string;principalDue:number;interestDue:number;penaltyDue:number;totalDue:number;oldestDue:string|null;dpd:number;bucket:string};
type ExceptionRow={type:string;reference:string;detail:string;href:string|null};
function money(value:unknown){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(value||0));}
function localToday(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
function daysPastDue(due:string|null,today:string){if(!due)return 0;const a=Date.parse(`${due}T00:00:00+07:00`),b=Date.parse(`${today}T00:00:00+07:00`);return Math.max(0,Math.floor((b-a)/86400000));}
function bucket(dpd:number){if(dpd<=0)return"LANCAR";if(dpd<=30)return"1–30 HARI";if(dpd<=60)return"31–60 HARI";if(dpd<=90)return"61–90 HARI";return"91+ HARI";}
function journalKey(type:string,id:string){return`${type}:${id}`;}
function journalByKey(rows:LoanAccountingJournalRow[]){return new Map(rows.map(row=>[journalKey(row.source_type,row.source_id),row]));}
function readableExceptionType(value:string){return value.replace(/_/g," ");}

export default async function LoanReportsPage(){
 const access=await getAccessContext();if(!access)redirect("/login");if(!access.permissions.includes("LOAN_REPORT_VIEW"))redirect("/dashboard");
 const schema=await getD1SchemaStatus();const supabase=await createClient();
 const [contractsResult,scheduleResult,disbursementsResult,repaymentsResult,reversalsResult]=await Promise.all([
  supabase.from("loan_contracts").select("id,contract_number,status,principal_amount,first_due_date").eq("organization_id",access.organization.id).in("status",["DISBURSED","CLOSED"]).limit(5000),
  supabase.from("loan_installment_schedule").select("contract_id,installment_number,due_date,principal_amount,interest_amount,paid_principal_amount,paid_interest_amount,penalty_assessed_amount,paid_penalty_amount,penalty_waived_amount,status").eq("organization_id",access.organization.id).limit(5000),
  supabase.from("loan_disbursements").select("id,contract_id,status,net_disbursement_amount,d1_journal_entry_id,disbursed_at").eq("organization_id",access.organization.id).eq("status","DISBURSED").limit(5000),
  supabase.from("loan_repayments").select("id,contract_id,status,principal_amount,interest_amount,penalty_amount,d1_journal_entry_id,posted_at").eq("organization_id",access.organization.id).eq("status","POSTED").limit(5000),
  supabase.from("loan_repayment_reversals").select("id,repayment_id,contract_id,status,reversal_d1_journal_entry_id,reversed_at").eq("organization_id",access.organization.id).eq("status","REVERSED").limit(5000),
 ]);
 const queryErrors=[contractsResult.error,scheduleResult.error,disbursementsResult.error,repaymentsResult.error,reversalsResult.error].filter(Boolean);
 const contracts=(contractsResult.data??[])as ContractRow[],schedule=(scheduleResult.data??[])as ScheduleRow[],disbursements=(disbursementsResult.data??[])as DisbursementRow[],repayments=(repaymentsResult.data??[])as RepaymentRow[],reversals=(reversalsResult.data??[])as ReversalRow[];
 const today=localToday();const schedulesByContract=new Map<string,ScheduleRow[]>();for(const row of schedule){const list=schedulesByContract.get(row.contract_id)||[];list.push(row);schedulesByContract.set(row.contract_id,list);}
 const aging:AgingRow[]=contracts.map(contract=>{const rows=schedulesByContract.get(contract.id)||[];let principalDue=0,interestDue=0,penaltyDue=0;let oldestDue:string|null=null;for(const row of rows){const p=Math.max(0,Number(row.principal_amount)-Number(row.paid_principal_amount));const i=Math.max(0,Number(row.interest_amount)-Number(row.paid_interest_amount));const f=Math.max(0,Number(row.penalty_assessed_amount)-Number(row.paid_penalty_amount)-Number(row.penalty_waived_amount));principalDue+=p;interestDue+=i;penaltyDue+=f;if(p+i+f>0&&(!oldestDue||row.due_date<oldestDue))oldestDue=row.due_date;}const dpd=daysPastDue(oldestDue,today);return{contractId:contract.id,contractNumber:contract.contract_number,status:contract.status,principalDue,interestDue,penaltyDue,totalDue:principalDue+interestDue+penaltyDue,oldestDue,dpd,bucket:bucket(dpd)};}).sort((a,b)=>b.dpd-a.dpd||b.totalDue-a.totalDue);
 const supabasePrincipal=aging.reduce((s,x)=>s+x.principalDue,0);const supabaseInterestDue=aging.reduce((s,x)=>s+x.interestDue,0);const supabasePenaltyDue=aging.reduce((s,x)=>s+x.penaltyDue,0);const nplProxy=aging.filter(x=>x.dpd>=91&&x.totalDue>0);const nplExposure=nplProxy.reduce((s,x)=>s+x.totalDue,0);
 let d1:null|Awaited<ReturnType<typeof getLoanAccountingSnapshot>>=null;let d1Error:string|null=null;if(schema.current&&schema.features.treasuryPeriod){try{d1=await getLoanAccountingSnapshot(access.organization.id);}catch(error){d1Error=error instanceof Error?error.message:"Rekonsiliasi pencatatan keuangan gagal.";}}
 const reversedRepaymentIds=new Set(reversals.map(x=>x.repayment_id));const expectedInterest=repayments.filter(x=>!reversedRepaymentIds.has(x.id)).reduce((s,x)=>s+Number(x.interest_amount),0);const expectedPenalty=repayments.filter(x=>!reversedRepaymentIds.has(x.id)).reduce((s,x)=>s+Number(x.penalty_amount),0);
 const exceptions:ExceptionRow[]=[];if(d1){const byKey=journalByKey(d1.journals);for(const row of disbursements){const j=byKey.get(journalKey("LOAN_DISBURSEMENT",row.id));if(!j)exceptions.push({type:"JURNAL_TIDAK_ADA",reference:row.id,detail:"Pencairan yang selesai belum mempunyai jurnal keuangan.",href:`/loans/disbursements/${row.id}`});else if(j.journal_id!==row.d1_journal_entry_id||j.receivable_net!==Number(row.net_disbursement_amount)||!j.balanced)exceptions.push({type:"TIDAK_COCOK",reference:row.id,detail:`Nilai pencairan dan piutang tidak cocok (${money(j.receivable_net)} vs ${money(row.net_disbursement_amount)}).`,href:`/loans/disbursements/${row.id}`});}
  const repaymentMap=new Map(repayments.map(x=>[x.id,x]));for(const row of repayments){const j=byKey.get(journalKey("LOAN_REPAYMENT",row.id));if(!j)exceptions.push({type:"JURNAL_TIDAK_ADA",reference:row.id,detail:"Angsuran yang selesai belum mempunyai jurnal keuangan.",href:`/loans/repayments/${row.id}`});else if(j.journal_id!==row.d1_journal_entry_id||j.receivable_net!==-Number(row.principal_amount)||j.interest_revenue_net!==Number(row.interest_amount)||j.penalty_revenue_net!==Number(row.penalty_amount)||!j.balanced)exceptions.push({type:"TIDAK_COCOK",reference:row.id,detail:"Komponen jurnal angsuran tidak sama dengan transaksi sumber.",href:`/loans/repayments/${row.id}`});}
  for(const row of reversals){const original=repaymentMap.get(row.repayment_id);const j=byKey.get(journalKey("LOAN_REPAYMENT_REVERSAL",row.id));if(!j)exceptions.push({type:"JURNAL_TIDAK_ADA",reference:row.id,detail:"Pembalikan angsuran belum mempunyai jurnal keuangan.",href:"/loans/corrections"});else if(!original||j.journal_id!==row.reversal_d1_journal_entry_id||j.receivable_net!==Number(original.principal_amount)||j.interest_revenue_net!==-Number(original.interest_amount)||j.penalty_revenue_net!==-Number(original.penalty_amount)||!j.balanced)exceptions.push({type:"TIDAK_COCOK",reference:row.id,detail:"Jurnal pembalikan tidak merupakan kebalikan transaksi angsuran asal.",href:"/loans/corrections"});}
  const expectedSources=new Set([...disbursements.map(x=>journalKey("LOAN_DISBURSEMENT",x.id)),...repayments.map(x=>journalKey("LOAN_REPAYMENT",x.id)),...reversals.map(x=>journalKey("LOAN_REPAYMENT_REVERSAL",x.id))]);for(const j of d1.journals){const key=journalKey(j.source_type,j.source_id);if(!expectedSources.has(key))exceptions.push({type:"JURNAL_TANPA_SUMBER",reference:j.journal_id,detail:"Jurnal pinjaman tidak memiliki transaksi final pasangan.",href:`/finance/journals/${j.journal_id}`});}for(const key of d1.duplicateSources)exceptions.push({type:"SUMBER_GANDA",reference:key,detail:"Lebih dari satu jurnal memakai sumber transaksi yang sama.",href:null});for(const id of d1.unbalancedJournalIds)exceptions.push({type:"JURNAL_TIDAK_SEIMBANG",reference:id,detail:"Jurnal pinjaman tidak seimbang.",href:`/finance/journals/${id}`});}
 const receivableGap=d1?d1.receivableBalance-supabasePrincipal:0,interestGap=d1?d1.interestRevenue-expectedInterest:0,penaltyGap=d1?d1.penaltyRevenue-expectedPenalty:0;const passed=!!d1&&queryErrors.length===0&&exceptions.length===0&&receivableGap===0&&interestGap===0&&penaltyGap===0;
 const buckets=["LANCAR","1–30 HARI","31–60 HARI","61–90 HARI","91+ HARI"].map(name=>{const rows=aging.filter(x=>x.bucket===name&&x.totalDue>0);return{name,count:rows.length,amount:rows.reduce((s,x)=>s+x.totalDue,0)};});

 return <PageContainer size="full">
  <PageHeader eyebrow="Simpan Pinjam · Laporan" title="Rekonsiliasi Pinjaman" description="Bandingkan sisa kewajiban pinjaman dengan pencatatan keuangan. Setiap selisih ditampilkan apa adanya untuk diperiksa." actions={<Badge tone={passed?"success":"warning"}>{passed?"Sesuai":"Perlu Diperiksa"} · {today}</Badge>}/>
  {!schema.current?<Alert tone="danger">Pencatatan keuangan belum siap untuk menjalankan rekonsiliasi.</Alert>:null}{d1Error?<Alert tone="danger">{d1Error}</Alert>:null}{queryErrors.length?<Alert tone="danger">Sebagian data pinjaman belum dapat dibaca.</Alert>:null}

  <section className={styles.metrics}><Card density="compact"><span>Sisa Pokok</span><strong>{money(supabasePrincipal)}</strong><small>berdasarkan jadwal pinjaman</small></Card><Card density="compact"><span>Saldo Piutang</span><strong>{money(d1?.receivableBalance||0)}</strong><small>selisih {money(receivableGap)}</small></Card><Card density="compact"><span>Bunga Terealisasi</span><strong>{money(d1?.interestRevenue||0)}</strong><small>seharusnya {money(expectedInterest)}</small></Card><Card density="compact"><span>Denda Terealisasi</span><strong>{money(d1?.penaltyRevenue||0)}</strong><small>seharusnya {money(expectedPenalty)}</small></Card></section>

  <section className={styles.detailGrid}><Card className={styles.panel}><div className={styles.panelHead}><div><span>Tunggakan</span><h3>Umur Tunggakan</h3></div><Badge>{aging.filter(x=>x.totalDue>0).length}</Badge></div><div className={styles.tableWrap}><table><thead><tr><th>Kelompok</th><th>Kontrak</th><th>Nilai</th></tr></thead><tbody>{buckets.map(x=><tr key={x.name}><td><strong>{x.name}</strong></td><td>{x.count}</td><td>{money(x.amount)}</td></tr>)}</tbody></table></div><p className={styles.formNote}>Kelompok 91+ hari digunakan sebagai indikator operasional untuk perhatian lebih lanjut.</p></Card><Card className={styles.panel}><div className={styles.panelHead}><div><span>Kontrol</span><h3>Kontrol Rekonsiliasi</h3></div><Badge tone={exceptions.length?"warning":"success"}>{exceptions.length} temuan</Badge></div><dl className={styles.definition}><div><dt>Bunga Belum Dibayar</dt><dd>{money(supabaseInterestDue)}</dd></div><div><dt>Denda Belum Dibayar</dt><dd>{money(supabasePenaltyDue)}</dd></div><div><dt>Tunggakan 91+ Hari</dt><dd>{money(nplExposure)}</dd></div><div><dt>Kontrak 91+ Hari</dt><dd>{nplProxy.length}</dd></div><div><dt>Selisih Bunga</dt><dd>{money(interestGap)}</dd></div><div><dt>Selisih Denda</dt><dd>{money(penaltyGap)}</dd></div><div><dt>Temuan</dt><dd>{exceptions.length}</dd></div><div><dt>Jurnal Pinjaman</dt><dd>{d1?.journals.length||0}</dd></div></dl></Card></section>

  <Card className={styles.panel}><div className={styles.panelHead}><div><span>Detail Kewajiban</span><h3>Kontrak dengan Kewajiban Tersisa</h3></div><Badge>{aging.filter(x=>x.totalDue>0).length}</Badge></div>{aging.some(x=>x.totalDue>0)?<div className={styles.tableWrap}><table><thead><tr><th>Kontrak</th><th>Jatuh Tempo Terlama</th><th>Hari Tertunggak</th><th>Pokok</th><th>Bunga</th><th>Denda</th><th>Total</th></tr></thead><tbody>{aging.filter(x=>x.totalDue>0).slice(0,250).map(x=><tr key={x.contractId}><td><Link href={`/loans/contracts/${x.contractId}`}><strong>{x.contractNumber}</strong></Link><small>{x.bucket}</small></td><td>{x.oldestDue||"—"}</td><td>{x.dpd}</td><td>{money(x.principalDue)}</td><td>{money(x.interestDue)}</td><td>{money(x.penaltyDue)}</td><td><strong>{money(x.totalDue)}</strong></td></tr>)}</tbody></table></div>:<div className={styles.empty}>Tidak ada kontrak dengan kewajiban tersisa.</div>}</Card>

  <details className={styles.technicalDetails}><summary>Temuan & Detail Rekonsiliasi <Badge tone={exceptions.length?"warning":"success"}>{exceptions.length}</Badge></summary><div className={styles.technicalBody}>{exceptions.length?<div className={styles.tableWrap}><table><thead><tr><th>Jenis</th><th>Referensi</th><th>Detail</th><th></th></tr></thead><tbody>{exceptions.slice(0,250).map((x,i)=><tr key={`${x.type}-${x.reference}-${i}`}><td><strong>{readableExceptionType(x.type)}</strong></td><td><small>{x.reference}</small></td><td>{x.detail}</td><td>{x.href?<Link href={x.href}>Periksa</Link>:"—"}</td></tr>)}</tbody></table></div>:<Alert tone="success">Tidak ada temuan rekonsiliasi. Pencatatan pinjaman dan jurnal keuangan cocok.</Alert>}<p className={styles.formNote}>Sisa pokok dibandingkan dengan akun piutang pinjaman. Bunga dan denda dibandingkan dengan pembayaran yang sudah selesai setelah memperhitungkan transaksi yang dibalik.</p></div></details>
 </PageContainer>;
}
