import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { getAccessContext } from "@/lib/access/context";
import { getD1SchemaStatus } from "@/lib/d1/context";
import { getStockOpnameSession } from "@/lib/d1/opname";
import { PageContainer,PageHeader } from "@/components/ui/page-layout";
import { Card } from "@/components/ui/card";
import { Alert } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { SensitiveAction } from "@/components/domain/transaction-components";
import { approveAndPostStockOpnameAction,cancelStockOpnameAction,recordStockOpnameCountAction,submitStockOpnameAction } from "../actions";
import styles from "../opname.module.css";

export const dynamic="force-dynamic";
type PageProps={params:Promise<{id:string}>;searchParams:Promise<{status?:string;error?:string}>};
function rupiah(value:number){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(value)}
function timestamp(value:string|null){if(!value)return"—";return new Date(value).toLocaleString("id-ID",{timeZone:"Asia/Jakarta",dateStyle:"medium",timeStyle:"short"})}
function statusTone(status:string):"success"|"warning"|"info"|"danger"|"neutral"{if(status==="POSTED")return"success";if(status==="CANCELLED")return"neutral";if(status==="COUNTED"||status==="APPROVED")return"warning";return"info"}

export default async function StockOpnameDetailPage({params,searchParams}:PageProps){
 const access=await getAccessContext();if(!access)redirect("/login");if(!access.permissions.includes("INVENTORY_VIEW"))redirect("/dashboard");const schema=await getD1SchemaStatus();if(!schema.current)redirect("/setup/database");
 const {id}=await params;const query=await searchParams;const detail=await getStockOpnameSession(access.organization.id,id);if(!detail)notFound();
 const canManage=access.permissions.includes("ORG_MANAGE");const editable=canManage&&["DRAFT","COUNTING"].includes(detail.session.status);const countedLines=detail.lines.filter((line)=>line.physical_qty!==null).length;const varianceLines=detail.lines.filter((line)=>Number(line.variance_qty||0)!==0).length;const netVariance=detail.lines.reduce((sum,line)=>sum+Number(line.variance_qty||0),0);const varianceValue=detail.lines.reduce((sum,line)=>sum+Number(line.variance_qty||0)*Number(line.unit_cost_amount||0),0);
 return <PageContainer size="wide">
  <PageHeader eyebrow={`Stock Opname · ${detail.session.warehouse_code}`} title={detail.session.session_number} description={`${detail.session.warehouse_name} · dibuat ${timestamp(detail.session.created_at)} · ${detail.session.notes||"tanpa catatan khusus"}`} actions={<div className={styles.topActions}><Badge tone={statusTone(detail.session.status)}>{detail.session.status}</Badge><Link className={styles.detailLink} href="/inventory/opname">Kembali</Link></div>}/>
  {query.status==="created"?<Alert tone="success" title="Snapshot dibuat">Mulai hitung fisik per produk.</Alert>:null}{query.status==="count-saved"?<Alert tone="success" title="Hasil hitung tersimpan">Baris opname berhasil diperbarui.</Alert>:null}{query.status==="counted"?<Alert tone="success" title="Hasil hitung disubmit">Sesi siap untuk review dan posting adjustment.</Alert>:null}{query.status==="posted"?<Alert tone="success" title="Opname diposting">Adjustment selisih sudah masuk inventory ledger.</Alert>:null}{query.error?<Alert tone="danger" title="Opname belum dapat diproses">{query.error}</Alert>:null}

  <section className={styles.metrics}><Card density="compact"><span>Produk snapshot</span><strong>{detail.lines.length}</strong><small>tracked-stock items</small></Card><Card density="compact"><span>Sudah dihitung</span><strong>{countedLines}</strong><small>dari {detail.lines.length}</small></Card><Card density="compact"><span>Baris selisih</span><strong>{varianceLines}</strong><small>butuh alasan jika ≠ 0</small></Card><Card density="compact"><span>Net variance</span><strong>{netVariance>0?`+${netVariance}`:netVariance}</strong><small>{rupiah(varianceValue)}</small></Card></section>

  <section className={styles.workflowBar}><div className={["DRAFT","COUNTING"].includes(detail.session.status)?styles.currentStep:styles.doneStep}><b>01</b><span>Hitung fisik</span></div><div className={detail.session.status==="COUNTED"?styles.currentStep:["POSTED","APPROVED"].includes(detail.session.status)?styles.doneStep:styles.futureStep}><b>02</b><span>Submit & review</span></div><div className={detail.session.status==="POSTED"?styles.doneStep:styles.futureStep}><b>03</b><span>Post adjustment</span></div></section>

  <Card className={styles.panel}><div className={styles.panelHead}><div><span className={styles.kicker}>COUNT SHEET</span><h2>System stock vs physical stock</h2></div><Badge>{countedLines}/{detail.lines.length} saved</Badge></div><div className={styles.countList}>{detail.lines.map((line)=>{const variance=Number(line.variance_qty||0);return <article className={`${styles.countRow} ${variance!==0?styles.countVariance:""}`} key={line.id}><div className={styles.productCopy}><span>{line.sku}</span><strong>{line.product_name}</strong><small>HPP {rupiah(line.unit_cost_amount)} · {line.unit_name}</small></div><div className={styles.systemQty}><span>System</span><strong>{line.system_qty}</strong></div>{editable?<form action={recordStockOpnameCountAction} className={styles.countForm}><input type="hidden" name="sessionId" value={id}/><input type="hidden" name="lineId" value={line.id}/><label>Fisik<input name="physicalQty" type="number" min="0" step="1" required defaultValue={line.physical_qty??""} placeholder={String(line.system_qty)}/></label><label>Alasan selisih<input name="reasonText" maxLength={200} defaultValue={line.reason_text||""} placeholder="Wajib bila fisik ≠ sistem"/></label><label>Bukti/ref<input name="evidenceReference" maxLength={240} defaultValue={line.evidence_reference||""} placeholder="Foto/doc/reference opsional"/></label><button type="submit">Simpan</button></form>:<div className={styles.readCount}><div><span>Fisik</span><strong>{line.physical_qty??"—"}</strong></div><div><span>Variance</span><strong className={variance===0?styles.okText:styles.warnText}>{variance>0?`+${variance}`:variance}</strong></div><p>{line.reason_text||"Tidak ada alasan selisih."}</p>{line.evidence_reference?<small>Bukti: {line.evidence_reference}</small>:null}</div>}{editable&&line.physical_qty!==null?<div className={styles.savedVariance}><span>Saved variance</span><strong className={variance===0?styles.okText:styles.warnText}>{variance>0?`+${variance}`:variance}</strong></div>:null}</article>})}</div></Card>

  {canManage?<Card className={styles.actionPanel}><div><span className={styles.kicker}>CONTROL ACTION</span><h2>Submit atau selesaikan opname</h2><p>Posting hanya diperbolehkan setelah semua baris dihitung. Runtime juga memeriksa ulang perubahan stok terhadap snapshot sebelum adjustment dilakukan.</p></div><div className={styles.actionButtons}>{["DRAFT","COUNTING"].includes(detail.session.status)?<form action={submitStockOpnameAction}><input type="hidden" name="sessionId" value={id}/><button className={styles.primaryAction} type="submit" disabled={countedLines!==detail.lines.length}>Submit Hasil Hitung</button></form>:null}{detail.session.status==="COUNTED"?<SensitiveAction summary="Approve & Post Adjustment" impact={<><strong>Dampak tindakan</strong><span>Variance fisik yang valid akan diposting sebagai movement adjustment ke inventory ledger. Histori snapshot/count tetap dipertahankan.</span></>}><form action={approveAndPostStockOpnameAction}><input type="hidden" name="sessionId" value={id}/><button className={styles.primaryAction} type="submit">Konfirmasi Posting Adjustment</button></form></SensitiveAction>:null}{["DRAFT","COUNTING","COUNTED"].includes(detail.session.status)?<form action={cancelStockOpnameAction}><input type="hidden" name="sessionId" value={id}/><button className={styles.secondaryAction} type="submit">Batalkan Opname</button></form>:null}</div></Card>:null}
  <Alert tone="info" title="Control note">Seluruh perubahan opname tetap melalui permission inventory control, server action yang sama, snapshot validation, dan transaction audit. Migrasi ini hanya mengubah presentation layer.</Alert>
 </PageContainer>;
}
